/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Admin;

import DAO.KhaoSatDAO;
import DAO.QuanNhanDAO;
import Model.CapBac;
import Model.DonVi;
import Model.QuanNhan;
import Service.Validation;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.image.ImageObserver.WIDTH;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.TimerTask;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author DELL
 */
public final class QuanLyQuanNhan extends javax.swing.JPanel {
    QuanNhanDAO qndao = new QuanNhanDAO();
    KhaoSatDAO ksdao = new KhaoSatDAO();
    DefaultTableModel tableModel = new DefaultTableModel();
    
    Timer timer;
    int idQN = -1;
    
    /**
     * Creates new form ManagerUser
     */
    public QuanLyQuanNhan() {
        initComponents();
        tableModel = (DefaultTableModel) tableQuanNhan.getModel();
        showQuanNhan(list);
        showCapBac(ksdao.selectCapBac());
        showDonVi(qndao.selectDonVi());
        jTTKhoaTK.setVisible(false);
        jButtonKhoaTK.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupFilter = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableQuanNhan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonCRUD = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnKhoaTaiKhoan = new javax.swing.JButton();
        jButtonKhoaTK = new javax.swing.JPanel();
        btnH = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        jTTDangKy = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateNgaySinh = new com.toedter.calendar.JDateChooser();
        cbCapBac = new javax.swing.JComboBox<>();
        cbDonVi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtTenTK = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMatkhau = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCmnd = new javax.swing.JTextField();
        jTTKhoaTK = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jThoigiankhoa = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLydokhoa = new javax.swing.JTextArea();
        jTenTK = new javax.swing.JLabel();
        jEmail = new javax.swing.JLabel();
        jCmnd = new javax.swing.JLabel();
        jTenqn = new javax.swing.JLabel();
        jNgaykhoa = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtNameFilter = new javax.swing.JTextField();
        cbTrangThai = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        rdFilterName = new javax.swing.JRadioButton();
        rdFilterStatus = new javax.swing.JRadioButton();
        btnHuyTimKiem = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jLabel1.setBackground(new java.awt.Color(0, 153, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("QUẢN LÝ TÀI KHOẢN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(462, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(403, 403, 403))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 50));

        tableQuanNhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên tài khoản", "Mật khẩu", "Email", "CMND", "Họ và Tên", "Ngày Sinh", "Cấp bậc", "Đơn vị", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableQuanNhan.setRowHeight(30);
        tableQuanNhan.setShowHorizontalLines(true);
        tableQuanNhan.setShowVerticalLines(true);
        tableQuanNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableQuanNhanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableQuanNhan);
        if (tableQuanNhan.getColumnModel().getColumnCount() > 0) {
            tableQuanNhan.getColumnModel().getColumn(0).setMaxWidth(50);
            tableQuanNhan.getColumnModel().getColumn(1).setMinWidth(150);
            tableQuanNhan.getColumnModel().getColumn(2).setMaxWidth(100);
            tableQuanNhan.getColumnModel().getColumn(3).setMinWidth(120);
            tableQuanNhan.getColumnModel().getColumn(4).setMinWidth(120);
            tableQuanNhan.getColumnModel().getColumn(5).setMinWidth(150);
            tableQuanNhan.getColumnModel().getColumn(6).setMinWidth(30);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1120, 360));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCRUD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThem.setBackground(new java.awt.Color(0, 153, 0));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 0));
        btnThem.setText("Thêm Mới");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jButtonCRUD.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 140, 30));

        btnCapNhat.setBackground(new java.awt.Color(0, 51, 255));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 0));
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        jButtonCRUD.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 48, 140, 30));

        btnXoa.setBackground(new java.awt.Color(255, 0, 0));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 0));
        btnXoa.setText("Xóa ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jButtonCRUD.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 95, 140, 30));

        btnKhoaTaiKhoan.setBackground(new java.awt.Color(102, 0, 102));
        btnKhoaTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKhoaTaiKhoan.setForeground(new java.awt.Color(255, 255, 0));
        btnKhoaTaiKhoan.setText("Khóa Tài Khoản");
        btnKhoaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaTaiKhoanActionPerformed(evt);
            }
        });
        jButtonCRUD.add(btnKhoaTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 140, 30));

        jPanel2.add(jButtonCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, 6, 142, 178));

        btnH.setBackground(new java.awt.Color(255, 255, 0));
        btnH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnH.setForeground(new java.awt.Color(0, 102, 102));
        btnH.setText("Hủy");
        btnH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHActionPerformed(evt);
            }
        });

        btnK.setBackground(new java.awt.Color(255, 51, 0));
        btnK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnK.setForeground(new java.awt.Color(102, 0, 102));
        btnK.setText("Khóa");
        btnK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jButtonKhoaTKLayout = new javax.swing.GroupLayout(jButtonKhoaTK);
        jButtonKhoaTK.setLayout(jButtonKhoaTKLayout);
        jButtonKhoaTKLayout.setHorizontalGroup(
            jButtonKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jButtonKhoaTKLayout.createSequentialGroup()
                .addGroup(jButtonKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnK, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE))
                .addContainerGap())
        );
        jButtonKhoaTKLayout.setVerticalGroup(
            jButtonKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jButtonKhoaTKLayout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(btnK, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnH, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        jPanel2.add(jButtonKhoaTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 140, 190));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Tên Quân Nhân");

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Ngày Sinh");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Cấp Bậc");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Đơn Vị");

        dateNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Tên Tài Khoản:");

        txtTenTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Mật Khẩu:");

        txtMatkhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("Email:");

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("CMND:");

        txtCmnd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        javax.swing.GroupLayout jTTDangKyLayout = new javax.swing.GroupLayout(jTTDangKy);
        jTTDangKy.setLayout(jTTDangKyLayout);
        jTTDangKyLayout.setHorizontalGroup(
            jTTDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTTDangKyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jTTDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTTDangKyLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMatkhau))
                    .addGroup(jTTDangKyLayout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEmail))
                    .addGroup(jTTDangKyLayout.createSequentialGroup()
                        .addGroup(jTTDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jTTDangKyLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCmnd))
                            .addGroup(jTTDangKyLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTenTK, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(35, 35, 35)
                .addGroup(jTTDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jTTDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jTTDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(cbCapBac, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dateNgaySinh, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                        .addComponent(cbDonVi, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jTTDangKyLayout.setVerticalGroup(
            jTTDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTTDangKyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jTTDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jTTDangKyLayout.createSequentialGroup()
                        .addGroup(jTTDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jTTDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dateNgaySinh, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(19, 19, 19)
                        .addGroup(jTTDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCapBac, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jTTDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbDonVi, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jTTDangKyLayout.createSequentialGroup()
                        .addGroup(jTTDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtTenTK, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jTTDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMatkhau, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jTTDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jTTDangKyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtCmnd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))))
                .addGap(14, 14, 14))
        );

        jPanel2.add(jTTDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("Tên Tài Khoản:");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("Tên Quân Nhân");

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setText("CMND:");

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setText("Email:");

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Ngày Khóa:");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Khóa trong vòng:");

        jThoigiankhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "5 giây (Demo)", "5 ngày", "5 tháng" }));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Lý do khóa:");

        jLydokhoa.setColumns(20);
        jLydokhoa.setRows(5);
        jScrollPane2.setViewportView(jLydokhoa);

        javax.swing.GroupLayout jTTKhoaTKLayout = new javax.swing.GroupLayout(jTTKhoaTK);
        jTTKhoaTK.setLayout(jTTKhoaTKLayout);
        jTTKhoaTKLayout.setHorizontalGroup(
            jTTKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTTKhoaTKLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jTTKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jTTKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTenTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCmnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTenqn, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jTTKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addGap(18, 18, 18)
                .addGroup(jTTKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jTTKhoaTKLayout.createSequentialGroup()
                        .addComponent(jThoigiankhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE))
                    .addComponent(jNgaykhoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jTTKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jTTKhoaTKLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(576, Short.MAX_VALUE)))
        );
        jTTKhoaTKLayout.setVerticalGroup(
            jTTKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jTTKhoaTKLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jTTKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(jTenTK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jNgaykhoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jTTKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jTTKhoaTKLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jThoigiankhoa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jTTKhoaTKLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jTTKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jTTKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                            .addComponent(jCmnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jTTKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jTTKhoaTKLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jTTKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jTTKhoaTKLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jTenqn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(17, 17, 17))
            .addGroup(jTTKhoaTKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jTTKhoaTKLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(156, 156, 156)))
        );

        jPanel2.add(jTTKhoaTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 200));

        txtNameFilter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        cbTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trạng Thái", "Hoạt động", "Bị khóa" }));

        btnTimKiem.setBackground(new java.awt.Color(0, 153, 204));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 0));
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnGroupFilter.add(rdFilterName);
        rdFilterName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdFilterName.setText("Tìm Kiếm theo tên Quân Nhân");

        btnGroupFilter.add(rdFilterStatus);
        rdFilterStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdFilterStatus.setText("Tìm kiếm theo Trạng Thái");

        btnHuyTimKiem.setBackground(new java.awt.Color(255, 51, 0));
        btnHuyTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHuyTimKiem.setForeground(new java.awt.Color(255, 255, 0));
        btnHuyTimKiem.setText("Hủy Tìm Kiếm");
        btnHuyTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnHuyTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cbTrangThai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdFilterStatus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNameFilter)
                    .addComponent(rdFilterName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdFilterName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(txtNameFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdFilterStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHuyTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(872, 0, -1, 190));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1120, 190));
    }// </editor-fold>//GEN-END:initComponents

    private void tableQuanNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableQuanNhanMouseClicked
        idQN = Integer.parseInt(tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 0).toString());
        String tenTk = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 1).toString();
        String matkhau = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 2).toString();
        String email = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 3).toString();
        String cmnd = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 4).toString();
        String hoten = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 5).toString();
        String ngaysinh = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 6).toString();
        String capbac = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 7).toString();
        String donvi = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 8).toString();
        
        txtTenTK.setText(tenTk);
        txtMatkhau.setText(matkhau);
        txtEmail.setText(email);
        txtCmnd.setText(cmnd);
        txtHoTen.setText(hoten);
        
        jTenTK.setText(tenTk);
        jEmail.setText(email);
        jCmnd.setText(cmnd);
        jTenqn.setText(hoten);
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        jNgaykhoa.setText(java.time.LocalDateTime.now().format(formatter)+"");
        
        try {
            Date dateBth = new SimpleDateFormat("yyyy-MM-dd").parse(ngaysinh);
            dateNgaySinh.setDate(dateBth);
        } catch (ParseException ex) {
            System.out.println(ex.getMessage());
        }
        switch(capbac){
            case "Thiếu Úy" -> cbCapBac.setSelectedIndex(0);
            case "Trung Úy" -> cbCapBac.setSelectedIndex(1);
            case "Thượng Úy" -> cbCapBac.setSelectedIndex(2);
        }
        
        switch(donvi){
            case "Trung Đội I" -> cbDonVi.setSelectedIndex(0);
            case "Trung Đội II" -> cbDonVi.setSelectedIndex(1);
            case "Đại Đội III" -> cbDonVi.setSelectedIndex(2);
            case "Đại Đội IV" -> cbDonVi.setSelectedIndex(3);
        }
        
        
//        String image = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 8).toString();
//        if(!image.equals("null")){
//            ImageIcon imageIcon = new ImageIcon(image);
//            // Resize Image
//            Image imageResize = imageIcon.getImage().getScaledInstance(displayImage.getWidth(), displayImage.getHeight(), Image.SCALE_SMOOTH);
//            displayImage.setIcon(new ImageIcon(imageResize));
//        }
    }//GEN-LAST:event_tableQuanNhanMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if(Validation.isEmpty(txtTenTK.getText()) || Validation.isEmpty(txtMatkhau.getText()) || Validation.isEmpty(txtEmail.getText()) || Validation.isEmpty(txtCmnd.getText())
                || Validation.isEmpty(txtHoTen.getText()) || dateNgaySinh.getDate() == null){
            showError("Vui lòng điền đầy đủ thông tin");
        }
        else if(tableQuanNhan.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn tài khoản cần xóa","Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
        else{
            String id = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 0).toString();
            boolean delete = qndao.deleteQuanNhan(Integer.parseInt(id));
            if(!delete){
                JOptionPane.showMessageDialog(null, "Xóa Quân Nhân thành công");
                tableModel.removeRow(tableQuanNhan.getSelectedRow());
                reset();
            }else{
                JOptionPane.showMessageDialog(null, "Xóa Quân Nhân thất bại");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        String tenTk    = txtTenTK.getText();
        String matkhau  = txtMatkhau.getText();
        String email    = txtEmail.getText();
        String cmnd     = txtCmnd.getText();
        String hoten    = txtHoTen.getText();
        
        if(Validation.isEmpty(tenTk) || Validation.isEmpty(matkhau) || Validation.isEmpty(email) || Validation.isEmpty(cmnd)
                || Validation.isEmpty(hoten) || dateNgaySinh.getDate() == null){
            showError("Vui lòng điền đầy đủ thông tin");
        }else if(!ngayHopLe(dateNgaySinh.getDate())){
            showError("Ngày sinh không hợp lệ");
        }else{
            String id = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 0).toString();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String ngaySinh = dateFormat.format(dateNgaySinh.getDate());

            CapBac capBac = new CapBac(cbCapBac.getSelectedIndex() + 1, cbCapBac.getItemAt(cbCapBac.getSelectedIndex()));
            DonVi donVi   = new DonVi(cbDonVi.getSelectedIndex() + 1, cbDonVi.getItemAt(cbDonVi.getSelectedIndex()));
            
            QuanNhan quanNhan = new QuanNhan(Integer.parseInt(id),tenTk, matkhau, email, cmnd,hoten, 
                                        LocalDate.parse(ngaySinh), capBac, donVi,1,null);
            boolean update = qndao.updateQuanNhan(quanNhan);
            if(!update){
                JOptionPane.showMessageDialog(null, "Cập nhật Quân Nhân thành công");
                reset();
                tableQuanNhan.setValueAt(tenTk, tableQuanNhan.getSelectedRow(), 1);
                tableQuanNhan.setValueAt(matkhau, tableQuanNhan.getSelectedRow(), 2);
                tableQuanNhan.setValueAt(email, tableQuanNhan.getSelectedRow(), 3);
                tableQuanNhan.setValueAt(cmnd, tableQuanNhan.getSelectedRow(), 4);
                tableQuanNhan.setValueAt(hoten, tableQuanNhan.getSelectedRow(), 5);
                tableQuanNhan.setValueAt(ngaySinh, tableQuanNhan.getSelectedRow(), 6);
                tableQuanNhan.setValueAt(cbCapBac.getItemAt(cbCapBac.getSelectedIndex()), tableQuanNhan.getSelectedRow(), 7);
                tableQuanNhan.setValueAt(cbDonVi.getItemAt(cbDonVi.getSelectedIndex()), tableQuanNhan.getSelectedRow(), 8);
            }else{
                JOptionPane.showMessageDialog(null, "Cập nhật Quân Nhân thất bại");
            }
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        if(rdFilterName.isSelected()){
            cbTrangThai.setSelectedIndex(0);
            String key = txtNameFilter.getText();
            if (key.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập tên Quân Nhân cần tìm kiếm!");
            } else {
                List<QuanNhan> listResult = searchQuanNhanByName(list, key);
                tableModel.setRowCount(0);
                showQuanNhan(listResult);
            }
        }else if(rdFilterStatus.isSelected()){
            List<QuanNhan> listResult = new ArrayList<>();
            String key = cbTrangThai.getItemAt(cbTrangThai.getSelectedIndex());
            
            if(key.equals("Trạng Thái")){
                JOptionPane.showMessageDialog(null, "Vui lòng lựa chọn trạng thái tìm kiếm");
            }else{
                for (QuanNhan quanNhan : list) {
                    if(key.equalsIgnoreCase(quanNhan.getTrangThai())){
                        listResult.add(quanNhan);
                    }
                }
                tableModel.setRowCount(0);
                showQuanNhan(listResult);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng lựa chọn hình thức tìm kiếm !");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnHuyTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyTimKiemActionPerformed
        List<QuanNhan> list = qndao.selectQuanNhan();
        txtNameFilter.setText("");
        cbTrangThai.setSelectedIndex(0);
        btnGroupFilter.clearSelection();
        tableModel.setRowCount(0);
        showQuanNhan(list);
    }//GEN-LAST:event_btnHuyTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String tenTk    = txtTenTK.getText();
        String matkhau  = txtMatkhau.getText();
        String email    = txtEmail.getText();
        String cmnd     = txtCmnd.getText();
        String hoten    = txtHoTen.getText();
        
        if(Validation.isEmpty(tenTk) || Validation.isEmpty(matkhau) || Validation.isEmpty(email) || Validation.isEmpty(cmnd)
                || Validation.isEmpty(hoten) || dateNgaySinh.getDate() == null){
            showError("Vui lòng điền đầy đủ thông tin");
        }else if(!ngayHopLe(dateNgaySinh.getDate())){
            showError("Ngày sinh không hợp lệ");
        }
        else{
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String ngaySinh = dateFormat.format(dateNgaySinh.getDate());
            
            CapBac capBac = new CapBac(cbCapBac.getSelectedIndex() + 1, cbCapBac.getItemAt(cbCapBac.getSelectedIndex()));
            DonVi donVi   = new DonVi(cbDonVi.getSelectedIndex() + 1, cbDonVi.getItemAt(cbDonVi.getSelectedIndex()));
            
            QuanNhan quanNhan = new QuanNhan(tenTk, matkhau, email, cmnd,hoten, LocalDate.parse(ngaySinh), capBac, donVi,1,"Hoạt động");
            
            if(qndao.them(quanNhan)){
                JOptionPane.showMessageDialog(null, "Thêm Quân Nhân thành công");
                tableModel.setRowCount(0);
                List<QuanNhan> list = qndao.selectQuanNhan();
                showQuanNhan(list);
                reset();
            }else{
                JOptionPane.showMessageDialog(null, "Thêm Quân Nhân thất bại");
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnKhoaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaTaiKhoanActionPerformed
        if(tableQuanNhan.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn tài khoản cần khóa","Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
        else{
            jTTDangKy.setVisible(false);
            jTTKhoaTK.setVisible(true);
            jButtonCRUD.setVisible(false);
            jButtonKhoaTK.setVisible(true);
        }
        
    }//GEN-LAST:event_btnKhoaTaiKhoanActionPerformed

    private void btnHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHActionPerformed
       jTTDangKy.setVisible(true);
       jTTKhoaTK.setVisible(false);
       jButtonKhoaTK.setVisible(false);
       jButtonCRUD.setVisible(true);
    }//GEN-LAST:event_btnHActionPerformed

    private void btnKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKActionPerformed
        String lydo = jLydokhoa.getText();
        String tg   = jThoigiankhoa.getItemAt(jThoigiankhoa.getSelectedIndex());
        
        if(Validation.isEmpty(lydo)){
            showError("Vui lòng điền lý do khóa tài khoản !");
        }
        else{
            // update trạng thái tài khoản thành "Đang khóa"
            // Bắt đầu chạy Timer theo thời gian cần khóa
            int tgKhoa = Integer.parseInt(tg.trim().split(" ")[0]);
            String mocThoiGian = tg.trim().split(" ")[1];
            if(!qndao.khoaTaiKhoan(idQN, "Bị khóa", lydo)){
                JOptionPane.showMessageDialog(null, "Khóa tài khoản thành công !");
                reset();
                tableModel.setRowCount(0);
                List<QuanNhan> list = qndao.selectQuanNhan();
                showQuanNhan(list);
                jTTDangKy.setVisible(true);
                jTTKhoaTK.setVisible(false);
                jButtonCRUD.setVisible(true);
                jButtonKhoaTK.setVisible(false);
                
            }else{
                JOptionPane.showMessageDialog(null, "Khóa tài khoản thất bại !");
            }
            
            long[] thoiGianChay = { 0 };
            long[] numberOfMilliseconds = { 0 };
            
            if(mocThoiGian.equalsIgnoreCase("giây")){
                numberOfMilliseconds[0] = tgKhoa * 1000;
            }else if(mocThoiGian.equalsIgnoreCase("ngày")){
                numberOfMilliseconds[0] = tgKhoa * 24 * 60 * 60 * 1000;
            }else if(mocThoiGian.equalsIgnoreCase("tháng")){
                numberOfMilliseconds[0] = tgKhoa * 30 * 24 * 60 * 60 * 1000;
            }
            
            Timer timer = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    thoiGianChay[0] += 1000;
                    if (thoiGianChay[0] >= numberOfMilliseconds[0]) {
                        // Đã chạy đủ 5 ngày, dừng Timer
                        ((Timer) e.getSource()).stop();

                        // Cập nhật trạng thái tài khoản
                        if(!qndao.khoaTaiKhoan(idQN, "Hoạt động", null)){
//                            JOptionPane.showMessageDialog(null, "Mở tài khoản thành công !");
                            
                            tableModel.setRowCount(0);
                            List<QuanNhan> list = qndao.selectQuanNhan();
                            showQuanNhan(list);
                        }
                    }
                }
            });

            // Bắt đầu timer
            timer.start();
        }
    }//GEN-LAST:event_btnKActionPerformed
    
    private boolean ngayHopLe(Date date){
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String ngay = dateFormat.format(date);
        
        LocalDate dateSS = LocalDate.parse(ngay);
        
        LocalDate dateCur = LocalDate.now();
        if(dateSS.isAfter(dateCur)){
            return false;
        }
        return true;
    }
    
    private List<QuanNhan> searchQuanNhanByName(List<QuanNhan> list, String key){
        List<QuanNhan> resultList = new ArrayList<>();
        var regex = ".*" + key + ".*";
        Pattern pattern = Pattern.compile(regex, Pattern.CASE_INSENSITIVE);
        Matcher matcher;
        for (QuanNhan quanNhan : list) {
            matcher = pattern.matcher(quanNhan.getHoTen());
            if (matcher.matches()) {
                resultList.add(quanNhan);
            }
        }
        return resultList;
    }
    
    private void showError(String str){
        JOptionPane.showMessageDialog(null, str,"Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    
    private void showCapBac(List<CapBac> list){
        for(int i = 0 ; i < list.size() ; i++){
            cbCapBac.addItem(list.get(i).getTenCapBac());
        }
    }
    private void showDonVi(List<DonVi> list){
        for(int i = 0 ; i < list.size() ; i++){
            cbDonVi.addItem(list.get(i).getTenDonVi());
        }
    }
    
    private void THeaderTable(){
        JTableHeader header = tableQuanNhan.getTableHeader();
        header.setFont(new Font("SansSerif", WIDTH, 14));
    }
    
    List<QuanNhan> list = qndao.selectQuanNhan();
    private void showQuanNhan(List<QuanNhan> list){
        THeaderTable();
        for (QuanNhan qn : list) {
            Object[] row = new Object[]{
                qn.getId(),qn.getTenTaiKhoan(),qn.getMatKhau(),qn.getEmail(),qn.getCmnd(),qn.getHoTen(),qn.getNgaySinh(),
                qn.getCapBac().getTenCapBac(), qn.getDonVi().getTenDonVi(), qn.getTrangThai()
            };
            tableModel.addRow(row);
        }
    }
    
    public void reset(){
        txtTenTK.setText("");
        txtMatkhau.setText("");
        txtEmail.setText("");
        txtCmnd.setText("");
        txtHoTen.setText("");
        dateNgaySinh.setDate(null);
        cbCapBac.setSelectedIndex(0);
        cbDonVi.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.ButtonGroup btnGroupFilter;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnHuyTimKiem;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnKhoaTaiKhoan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbCapBac;
    private javax.swing.JComboBox<String> cbDonVi;
    private javax.swing.JComboBox<String> cbTrangThai;
    private com.toedter.calendar.JDateChooser dateNgaySinh;
    private javax.swing.JPanel jButtonCRUD;
    private javax.swing.JPanel jButtonKhoaTK;
    private javax.swing.JLabel jCmnd;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jLydokhoa;
    private javax.swing.JLabel jNgaykhoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jTTDangKy;
    private javax.swing.JPanel jTTKhoaTK;
    private javax.swing.JLabel jTenTK;
    private javax.swing.JLabel jTenqn;
    private javax.swing.JComboBox<String> jThoigiankhoa;
    private javax.swing.JRadioButton rdFilterName;
    private javax.swing.JRadioButton rdFilterStatus;
    private javax.swing.JTable tableQuanNhan;
    private javax.swing.JTextField txtCmnd;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMatkhau;
    private javax.swing.JTextField txtNameFilter;
    private javax.swing.JTextField txtTenTK;
    // End of variables declaration//GEN-END:variables
}
