/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Admin;

import DAO.CauHoiDAO;
import DAO.KhaoSatDAO;
import Model.CapBac;
import Model.BaiKhaoSat;
import Model.CauHoi;
import Service.Validation;
import java.awt.Font;
import static java.awt.image.ImageObserver.WIDTH;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.xssf.usermodel.XSSFCell;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author DELL
 */
public class QuanLyBaiKhaoSat extends javax.swing.JPanel {
    KhaoSatDAO ksdao = new KhaoSatDAO();
    CauHoiDAO cauhoidao = new CauHoiDAO();
    DefaultTableModel tableModelBKS = new DefaultTableModel();
    DefaultTableModel tableModelCH = new DefaultTableModel();
    public boolean check = false;
    /**
     * Creates new form ManagerExam
     */
    public QuanLyBaiKhaoSat() {
        initComponents();
        showDoiTuong(ksdao.selectCapBac());
        tableModelBKS = (DefaultTableModel) tableBaiKhaoSat.getModel();
        tableModelCH = (DefaultTableModel) tableCauHoi.getModel();
        showDSBaiKhaoSat();
        JCauHoi.setVisible(false);

    }
    
    int idBKS = -1;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupFilter = new javax.swing.ButtonGroup();
        btnGroupHinhThucLC = new javax.swing.ButtonGroup();
        JContainer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        rdThoiGianTangDan = new javax.swing.JRadioButton();
        rdThoiGianGiamDan = new javax.swing.JRadioButton();
        btnTimKiem = new javax.swing.JButton();
        txtTenDe = new javax.swing.JTextField();
        rdTenDeThi = new javax.swing.JRadioButton();
        btnHuyTimKiem = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dateStart = new com.toedter.calendar.JDateChooser();
        dateEnd = new com.toedter.calendar.JDateChooser();
        cbTrangThai = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        cbDoiTuong = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        btnXoa = new javax.swing.JButton();
        btnChiTiet = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTieuDe = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableBaiKhaoSat = new javax.swing.JTable();
        JCauHoi = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jPanel13 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtNDCauHoi = new javax.swing.JTextArea();
        DonLuaChon = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        txtLC1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        txtLC2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        txtLC3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        txtLC4 = new javax.swing.JTextField();
        LuaChon = new javax.swing.JPanel();
        rdDonLC = new javax.swing.JRadioButton();
        rdDaLC = new javax.swing.JRadioButton();
        rdTuLuan = new javax.swing.JRadioButton();
        jPanel14 = new javax.swing.JPanel();
        btnImportExecel1 = new javax.swing.JButton();
        btnThemCauHoi = new javax.swing.JButton();
        btnCapNhatCauHoi = new javax.swing.JButton();
        btnXoaCauHoi = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableCauHoi = new javax.swing.JTable();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JContainer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 0));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("QUẢN LÝ BÀI KHẢO SÁT");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(424, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(413, 413, 413))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        JContainer.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Lọc Danh Sách Thi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14)))); // NOI18N

        btnGroupFilter.add(rdThoiGianTangDan);
        rdThoiGianTangDan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rdThoiGianTangDan.setText("Sắp xếp tăng dần theo thời gian thi");
        rdThoiGianTangDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdThoiGianTangDanActionPerformed(evt);
            }
        });

        btnGroupFilter.add(rdThoiGianGiamDan);
        rdThoiGianGiamDan.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        rdThoiGianGiamDan.setText("Sắp xếp giảm dần theo thời gian thi");
        rdThoiGianGiamDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdThoiGianGiamDanActionPerformed(evt);
            }
        });

        btnTimKiem.setBackground(new java.awt.Color(0, 153, 153));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 51));
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });

        btnGroupFilter.add(rdTenDeThi);
        rdTenDeThi.setText("Tìm kiếm theo Đối Tượng");
        rdTenDeThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTenDeThiActionPerformed(evt);
            }
        });

        btnHuyTimKiem.setBackground(new java.awt.Color(204, 0, 0));
        btnHuyTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHuyTimKiem.setForeground(new java.awt.Color(255, 255, 0));
        btnHuyTimKiem.setText("Hủy Tìm Kiếm");
        btnHuyTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(btnHuyTimKiem)
                        .addGap(18, 18, 18)
                        .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(rdThoiGianGiamDan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdThoiGianTangDan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rdTenDeThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(txtTenDe, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rdThoiGianTangDan, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rdThoiGianGiamDan, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rdTenDeThi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenDe, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnHuyTimKiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Tiêu đề khảo sát:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Trạng thái:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Thời gian bắt đầu:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel8.setText("Thời gian kết thúc:");

        cbTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Đang mở", "Đã đóng" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("Đối tượng:");

        cbDoiTuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        btnXoa.setBackground(new java.awt.Color(255, 51, 0));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 51));
        btnXoa.setText("Xóa Bài");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnChiTiet.setBackground(new java.awt.Color(204, 0, 204));
        btnChiTiet.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTiet.setForeground(new java.awt.Color(255, 255, 51));
        btnChiTiet.setText("Chi Tiết");
        btnChiTiet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietActionPerformed(evt);
            }
        });

        btnThem.setBackground(new java.awt.Color(0, 153, 0));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 51));
        btnThem.setText("Thêm Mới");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(51, 0, 255));
        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSua.setForeground(new java.awt.Color(255, 255, 51));
        btnSua.setText("Cập Nhật");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(btnSua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChiTiet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(btnThem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnChiTiet, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        txtTieuDe.setColumns(20);
        txtTieuDe.setRows(5);
        jScrollPane2.setViewportView(txtTieuDe);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dateEnd, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbDoiTuong, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(dateStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 15, Short.MAX_VALUE)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(dateStart, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbDoiTuong))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dateEnd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(cbTrangThai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        JContainer.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1120, 250));

        tableBaiKhaoSat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tiêu Đề", "Đối Tượng", "Thời gian bắt đầu", "Thời gian kết thúc", "Trạng thái"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableBaiKhaoSat.setRowHeight(40);
        tableBaiKhaoSat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableBaiKhaoSatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableBaiKhaoSat);
        if (tableBaiKhaoSat.getColumnModel().getColumnCount() > 0) {
            tableBaiKhaoSat.getColumnModel().getColumn(0).setMaxWidth(60);
            tableBaiKhaoSat.getColumnModel().getColumn(1).setMinWidth(300);
        }

        JContainer.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 1120, 300));

        add(JContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 620));

        JCauHoi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(0, 153, 0));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("QUẢN LÝ CÂU HỎI KHẢO SÁT");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap(387, Short.MAX_VALUE)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(379, 379, 379))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        JCauHoi.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 50));

        jPanel12.setBackground(new java.awt.Color(204, 204, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Câu hỏi khảo sát:");
        jPanel13.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 125, 53));

        txtNDCauHoi.setColumns(20);
        txtNDCauHoi.setRows(5);
        jScrollPane4.setViewportView(txtNDCauHoi);

        jPanel13.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 6, 590, 60));

        DonLuaChon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Lựa chọn 1:");
        DonLuaChon.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 106, 40));
        DonLuaChon.add(txtLC1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 590, 40));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Lựa chọn 2:");
        DonLuaChon.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 106, 40));
        DonLuaChon.add(txtLC2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 590, 40));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Lựa chọn 3:");
        DonLuaChon.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 106, 40));
        DonLuaChon.add(txtLC3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 590, 40));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Lựa chọn 4:");
        DonLuaChon.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 106, 40));
        DonLuaChon.add(txtLC4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 590, 40));

        jPanel13.add(DonLuaChon, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 78, 721, 192));

        btnGroupHinhThucLC.add(rdDonLC);
        rdDonLC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdDonLC.setText("Đơn lựa chọn");
        rdDonLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDonLCActionPerformed(evt);
            }
        });

        btnGroupHinhThucLC.add(rdDaLC);
        rdDaLC.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdDaLC.setText("Đa lựa chọn");
        rdDaLC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdDaLCActionPerformed(evt);
            }
        });

        btnGroupHinhThucLC.add(rdTuLuan);
        rdTuLuan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdTuLuan.setText("Tự luận");
        rdTuLuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTuLuanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout LuaChonLayout = new javax.swing.GroupLayout(LuaChon);
        LuaChon.setLayout(LuaChonLayout);
        LuaChonLayout.setHorizontalGroup(
            LuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
            .addGroup(LuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LuaChonLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(LuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(rdDaLC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rdDonLC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                        .addComponent(rdTuLuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        LuaChonLayout.setVerticalGroup(
            LuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 117, Short.MAX_VALUE)
            .addGroup(LuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(LuaChonLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(rdDonLC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(rdDaLC, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(12, 12, 12)
                    .addComponent(rdTuLuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jPanel13.add(LuaChon, new org.netbeans.lib.awtextra.AbsoluteConstraints(733, 6, -1, -1));

        jPanel12.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 270));

        btnImportExecel1.setBackground(new java.awt.Color(51, 102, 0));
        btnImportExecel1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnImportExecel1.setForeground(new java.awt.Color(255, 255, 255));
        btnImportExecel1.setText("Import Execel");
        btnImportExecel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImportExecel1ActionPerformed(evt);
            }
        });

        btnThemCauHoi.setBackground(new java.awt.Color(0, 153, 0));
        btnThemCauHoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThemCauHoi.setForeground(new java.awt.Color(255, 255, 255));
        btnThemCauHoi.setText("Thêm Mới");
        btnThemCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemCauHoiActionPerformed(evt);
            }
        });

        btnCapNhatCauHoi.setBackground(new java.awt.Color(0, 51, 255));
        btnCapNhatCauHoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhatCauHoi.setForeground(new java.awt.Color(255, 255, 255));
        btnCapNhatCauHoi.setText("Cập nhật");
        btnCapNhatCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatCauHoiActionPerformed(evt);
            }
        });

        btnXoaCauHoi.setBackground(new java.awt.Color(255, 0, 0));
        btnXoaCauHoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoaCauHoi.setForeground(new java.awt.Color(255, 255, 255));
        btnXoaCauHoi.setText("Xóa bỏ");
        btnXoaCauHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaCauHoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(71, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnThemCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addComponent(btnCapNhatCauHoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnXoaCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnImportExecel1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(btnImportExecel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnThemCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCapNhatCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnXoaCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel12.add(jPanel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 0, 200, 270));

        JCauHoi.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1120, 270));

        tableCauHoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Câu hỏi khảo sát", "Lựa chọn 1", "Lựa chọn 2", "Lựa chọn 3", "Lựa chọn 4", "Hình thức lựa chọn"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCauHoi.setRowHeight(40);
        tableCauHoi.setShowGrid(false);
        tableCauHoi.setShowHorizontalLines(true);
        tableCauHoi.setShowVerticalLines(true);
        tableCauHoi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCauHoiMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tableCauHoi);

        JCauHoi.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 1120, 300));

        add(JCauHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String tieude = txtTieuDe.getText();
        String doituong = cbDoiTuong.getItemAt(cbDoiTuong.getSelectedIndex());
        String trangthai = cbTrangThai.getItemAt(cbTrangThai.getSelectedIndex());
        
        if(Validation.isEmpty(tieude) || dateStart.getDate() == null || dateEnd.getDate() == null){
            showError("Vui lòng điền đầy đủ thông tin !");
        }else if(Validation.validDate(dateStart.getDate(), dateEnd.getDate())){
            showError("Ngày bắt đầu không hợp lệ !");
        }
        else if(!ngayHopLe(dateStart.getDate()) || !ngayHopLe(dateEnd.getDate())){
            showError("Ngày bắt đầu hoặc ngày kết thúc không hợp lệ !");
        }
        else{
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String start = dateFormat.format(dateStart.getDate());
            String end = dateFormat.format(dateEnd.getDate());
            LocalDate dateStart = LocalDate.parse(start);
            LocalDate dateEnd = LocalDate.parse(end);
            BaiKhaoSat baiKhaoSat = new BaiKhaoSat(tieude,doituong,dateStart,dateEnd,trangthai);

            if(!ksdao.Them(baiKhaoSat)){
                showMessage("Thêm Bài Khảo Sát thành công !");
                reset();
                showDSBaiKhaoSat();
            }else{
                showMessage("Thêm Bài Khảo Sát thất bại !");
            }
        }
        
        
    }//GEN-LAST:event_btnThemActionPerformed

    private void tableBaiKhaoSatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableBaiKhaoSatMouseClicked
        String loaiDe    = tableBaiKhaoSat.getValueAt(tableBaiKhaoSat.getSelectedRow(), 2).toString();
        String tenDe     = tableBaiKhaoSat.getValueAt(tableBaiKhaoSat.getSelectedRow(), 1).toString();
        String tgBatDau  = tableBaiKhaoSat.getValueAt(tableBaiKhaoSat.getSelectedRow(), 3).toString();
        String tgKetThuc = tableBaiKhaoSat.getValueAt(tableBaiKhaoSat.getSelectedRow(), 4).toString();
        String trangthai  = tableBaiKhaoSat.getValueAt(tableBaiKhaoSat.getSelectedRow(), 5).toString();
        
        switch(loaiDe){
            case "Thiếu Úy"  -> cbDoiTuong.setSelectedIndex(0);
            case "Trung Úy"  -> cbDoiTuong.setSelectedIndex(1);
            case "Thượng Úy" -> cbDoiTuong.setSelectedIndex(2);
        }
        txtTieuDe.setText(tenDe);
    
        switch(trangthai){
            case "Đang mở"  -> cbTrangThai.setSelectedIndex(0);
            case "Đã đóng"  -> cbTrangThai.setSelectedIndex(1);
        }
        
        try {
            Date dateS = new SimpleDateFormat("yyyy-MM-dd").parse(tgBatDau);
            Date dateE = new SimpleDateFormat("yyyy-MM-dd").parse(tgKetThuc);
            dateStart.setDate(dateS);
            dateEnd.setDate(dateE);
        } catch (ParseException e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_tableBaiKhaoSatMouseClicked

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        String tieude = txtTieuDe.getText();
        String doituong = cbDoiTuong.getItemAt(cbDoiTuong.getSelectedIndex());
        String trangthai = cbTrangThai.getItemAt(cbTrangThai.getSelectedIndex());
        
        if(Validation.isEmpty(tieude) || dateStart.getDate() == null || dateEnd.getDate() == null){
            showError("Vui lòng điền đầy đủ thông tin !");
        }else if(Validation.validDate(dateStart.getDate(), dateEnd.getDate())){
            showError("Ngày bắt đầu không hợp lệ !");
        }else{
            String id     = tableBaiKhaoSat.getValueAt(tableBaiKhaoSat.getSelectedRow(), 0).toString();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String start = dateFormat.format(dateStart.getDate());
            String end = dateFormat.format(dateEnd.getDate());
            LocalDate dateStart = LocalDate.parse(start);
            LocalDate dateEnd = LocalDate.parse(end);

            BaiKhaoSat baiKhaoSat = new BaiKhaoSat(Integer.parseInt(id), tieude, doituong, dateStart, dateEnd, trangthai);

            if(ksdao.update(baiKhaoSat) > 0){
                showMessage("Cập nhật Bài Khảo Sát thành công");
                reset();
                tableBaiKhaoSat.setValueAt(tieude,tableBaiKhaoSat.getSelectedRow(),1);
                tableBaiKhaoSat.setValueAt(doituong,tableBaiKhaoSat.getSelectedRow(),2);
                tableBaiKhaoSat.setValueAt(dateStart,tableBaiKhaoSat.getSelectedRow(),3);
                tableBaiKhaoSat.setValueAt(dateEnd,tableBaiKhaoSat.getSelectedRow(),4);
                tableBaiKhaoSat.setValueAt(trangthai,tableBaiKhaoSat.getSelectedRow(),5);
            }else{
                showMessage("Cập nhật Bài Khảo Sát thất bại");
            }
        }
        
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        try{
            String id  = tableBaiKhaoSat.getValueAt(tableBaiKhaoSat.getSelectedRow(), 0).toString();

            if(ksdao.delete(Integer.parseInt(id)) > 0){
                showMessage("Xóa Bài Khảo Sát thành công !");
                tableModelBKS.removeRow(tableBaiKhaoSat.getSelectedRow());
                reset();
            }else{
                showMessage("Xóa Bài Khảo Sát thất bại !");
            }
        }catch(ArrayIndexOutOfBoundsException e){
            showError("Vui lòng chọn hàng cần xóa");
        }
        
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnChiTietActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietActionPerformed
        if(tableBaiKhaoSat.getSelectedRowCount() == 1){
            JContainer.setVisible(false);
            JCauHoi.setVisible(true);
            tableModelCH = (DefaultTableModel) tableCauHoi.getModel();
            tableModelCH.setRowCount(0);
            int id = (int) tableBaiKhaoSat.getValueAt(tableBaiKhaoSat.getSelectedRow(), 0);
            idBKS  = id;
            List<CauHoi> list = ksdao.selectCauHoiOfBKS(idBKS);
            showQuestion(list);
        } else{
            if(tableBaiKhaoSat.getRowCount() == 0){
                JOptionPane.showMessageDialog(null, "Table hiện đang trống !","Cảnh báo", JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng bạn muốn xem chi tiết !","Lỗi",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnChiTietActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        if(rdTenDeThi.isSelected()){
            String key = txtTenDe.getText();
            if (key.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập Đối Tượng cần tìm kiếm!");
            } else {
                List<BaiKhaoSat> list = ksdao.selectBaiKhaoSat();
                List<BaiKhaoSat> listResult = searchBKSByDoiTuong(list, key);
                tableModelBKS.setRowCount(0);
                showTimKiem(listResult);
            }
        }else{
            showMessage("Vui lòng chọn hình thức tìm kiếm !");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnHuyTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyTimKiemActionPerformed
        txtTenDe.setText("");
        btnGroupFilter.clearSelection();
        tableModelBKS.setRowCount(0);
        showDSBaiKhaoSat();
    }//GEN-LAST:event_btnHuyTimKiemActionPerformed

    private void rdThoiGianTangDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdThoiGianTangDanActionPerformed
        btnTimKiem.setEnabled(false);
        List<BaiKhaoSat> list = ksdao.selectBaiKhaoSat();
        Collections.sort(list, new Comparator<BaiKhaoSat>() {
            @Override
            public int compare(BaiKhaoSat o1, BaiKhaoSat o2) {
                if(o1.getThoiGianBatDau().compareTo(o2.getThoiGianBatDau())  == 0){
                    return o1.getThoiGianKetThuc().compareTo(o2.getThoiGianKetThuc());
                }else{
                    return o1.getThoiGianBatDau().compareTo(o2.getThoiGianBatDau());
                }
            }
        });
        tableModelBKS.setRowCount(0);
        showTimKiem(list);
    }//GEN-LAST:event_rdThoiGianTangDanActionPerformed

    private void rdThoiGianGiamDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdThoiGianGiamDanActionPerformed
        btnTimKiem.setEnabled(false);
        List<BaiKhaoSat> list = ksdao.selectBaiKhaoSat();
        Collections.sort(list, new Comparator<BaiKhaoSat>() {
            @Override
            public int compare(BaiKhaoSat o1, BaiKhaoSat o2) {
                if(o2.getThoiGianBatDau().compareTo(o1.getThoiGianBatDau())  == 0){
                    return o2.getThoiGianKetThuc().compareTo(o1.getThoiGianKetThuc());
                }else{
                    return o2.getThoiGianBatDau().compareTo(o1.getThoiGianBatDau());
                }
            }
        });
        tableModelBKS.setRowCount(0);
        showTimKiem(list);
    }//GEN-LAST:event_rdThoiGianGiamDanActionPerformed

    private void rdTenDeThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTenDeThiActionPerformed
        btnTimKiem.setEnabled(true);
    }//GEN-LAST:event_rdTenDeThiActionPerformed

    private void rdDonLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDonLCActionPerformed
        txtLC1.setEnabled(true);
        txtLC2.setEnabled(true);
        txtLC3.setEnabled(true);
        txtLC4.setEnabled(true);
    }//GEN-LAST:event_rdDonLCActionPerformed

    private void btnImportExecel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImportExecel1ActionPerformed
        FileInputStream fileInputStream = null;
        BufferedInputStream bufferedInputStream = null;
        XSSFWorkbook fWorkbook = null;

        String path = "D:\\DTU\\KhoaLuanTotNghiep_052023\\CauHoi_KhaoSat";
        JFileChooser fileChooser = new JFileChooser(path);
        int execlChooser = fileChooser.showOpenDialog(null);

        if(execlChooser == JFileChooser.APPROVE_OPTION){
            File excelFile = fileChooser.getSelectedFile();
            try {
                fileInputStream = new FileInputStream(excelFile);
                bufferedInputStream = new BufferedInputStream(fileInputStream);

                fWorkbook = new XSSFWorkbook(bufferedInputStream);
                XSSFSheet excelSheet = fWorkbook.getSheetAt(0);

                List<CauHoi> list = new ArrayList<>();

                for(int i = 1 ; i <= excelSheet.getLastRowNum(); i++){
                    XSSFRow excelRow = excelSheet.getRow(i);

                    XSSFCell noidung        = excelRow.getCell(0);
                    XSSFCell hinhthuc       = excelRow.getCell(1);
                    XSSFCell lc01           = excelRow.getCell(2);
                    XSSFCell lc02           = excelRow.getCell(3);
                    XSSFCell lc03           = excelRow.getCell(4);
                    XSSFCell lc04           = excelRow.getCell(5);

                    CauHoi cauHoi = new CauHoi(noidung.toString(), hinhthuc.toString(), lc01.toString(),
                                        lc02.toString(), lc03.toString(), lc04.toString());
                    list.add(cauHoi);
                    System.out.println("i "+i);
                }

                if(cauhoidao.ThemListCauHoi(list, idBKS) && idBKS > 0){
                    showMessage("Thêm danh sách câu hỏi thành công !");
                    List<CauHoi> listShow = ksdao.selectCauHoiOfBKS(idBKS);
                    showQuestion(listShow);
                }else{
                    String msg = "Thêm câu hỏi thất bại !";
                    showMessage(msg);
                }
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ex) {
                Logger.getLogger(ManagerQuestion.class.getName()).log(Level.SEVERE, null, ex);
            }finally{
                try {
                    fileInputStream.close();
                    bufferedInputStream.close();
                    fWorkbook.close();
                } catch (IOException ex) {
                    Logger.getLogger(QuanLyBaiKhaoSat.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }//GEN-LAST:event_btnImportExecel1ActionPerformed

    private void btnThemCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemCauHoiActionPerformed
        
        String hinhThuc = "";
        if(rdDonLC.isSelected()){
            hinhThuc = "Đơn lựa chọn";
        }else if(rdDaLC.isSelected()){
            hinhThuc = "Đa lựa chọn";
        }else if(rdTuLuan.isSelected()){
            hinhThuc = "Tự luận";
        }
        System.out.println("hình thức: "+hinhThuc);
        if((!hinhThuc.equals("Tự luận")) && (Validation.isEmpty(txtNDCauHoi.getText()) || Validation.isEmpty(txtLC1.getText()) || Validation.isEmpty(txtLC2.getText())
                || Validation.isEmpty(txtLC3.getText()) || Validation.isEmpty(txtLC4.getText()))){
            showError("Vui lòng điền đầy đủ thông tinnnnn !");
        }else if("Tự luận".equals(hinhThuc) && Validation.isEmpty(txtNDCauHoi.getText())){
            showError("Vui lòng điền đầy đủ thông tin !");
        }
        else{
            CauHoi question = new CauHoi(txtNDCauHoi.getText(), txtLC1.getText(), txtLC2.getText()
                                        ,txtLC3.getText(), txtLC4.getText(),hinhThuc);

            if(!cauhoidao.Them(question,idBKS) && idBKS > 0){
                String msg = "Thêm câu hỏi thành công !";
                showMessage(msg);
                List<CauHoi> list = ksdao.selectCauHoiOfBKS(idBKS);
                showQuestion(list);
                resetCauHoi();
            }else{
                String msg = "Thêm câu hỏi thất bại !";
                showMessage(msg);
            }
        }

    }//GEN-LAST:event_btnThemCauHoiActionPerformed

    private void btnCapNhatCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatCauHoiActionPerformed
        if(tableCauHoi.getSelectedRowCount() == 1){
            String id = tableCauHoi.getValueAt(tableCauHoi.getSelectedRow(), 0).toString();
            
            String hinhThuc = "";
            if(rdDonLC.isSelected()){
                hinhThuc = "Đơn lựa chọn";
            }else if(rdDaLC.isSelected()){
                hinhThuc = "Đa lựa chọn";
            }else if(rdTuLuan.isSelected()){
                hinhThuc = "Tự luận";
            }

            if((!hinhThuc.equals("Tự luận")) && (Validation.isEmpty(txtNDCauHoi.getText()) || Validation.isEmpty(txtLC1.getText()) || Validation.isEmpty(txtLC2.getText())
                || Validation.isEmpty(txtLC3.getText()) || Validation.isEmpty(txtLC4.getText()))){
                showError("Vui lòng điền đầy đủ thông tin !");
            }else if("Tự luận".equals(hinhThuc) && Validation.isEmpty(txtNDCauHoi.getText())){
                showError("Vui lòng điền đầy đủ thông tin !");
            }else{
                
                String noidung = txtNDCauHoi.getText();
                String lc01    = txtLC1.getText();
                String lc02    = txtLC2.getText();
                String lc03    = txtLC3.getText();
                String lc04    = txtLC4.getText();

                CauHoi cauHoi  = new CauHoi(Integer.parseInt(id),noidung, lc01, lc02, lc03, lc04, hinhThuc);
                
                if(cauhoidao.update(cauHoi) > 0){
                    showMessage("Cập nhật Bài Khảo Sát thành công !");
                    tableModelCH.setValueAt(noidung, tableCauHoi.getSelectedRow(), 1);
                    tableModelCH.setValueAt(lc01, tableCauHoi.getSelectedRow(), 2);
                    tableModelCH.setValueAt(lc02, tableCauHoi.getSelectedRow(), 3);
                    tableModelCH.setValueAt(lc03, tableCauHoi.getSelectedRow(), 4);
                    tableModelCH.setValueAt(lc04, tableCauHoi.getSelectedRow(), 5);
                    tableModelCH.setValueAt(hinhThuc, tableCauHoi.getSelectedRow(), 6);
                    reset();
                }else{
                    showMessage("Cập nhật Bài Khảo Sát thất bại !");
                }
            }
        }else{
            if(tableCauHoi.getRowCount() == 0){
                JOptionPane.showMessageDialog(null, "Table hiện đang trống !","Cảnh báo", JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng bạn muốn cập nhật !","Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnCapNhatCauHoiActionPerformed

    private void btnXoaCauHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaCauHoiActionPerformed
        if(tableCauHoi.getSelectedRowCount() == 1){
            String id = tableCauHoi.getValueAt(tableCauHoi.getSelectedRow(), 0).toString();
            String hinhThuc = "";
            if(rdDonLC.isSelected()){
                hinhThuc = "Đơn lựa chọn";
            }else if(rdDaLC.isSelected()){
                hinhThuc = "Đa lựa chọn";
            }else if(rdTuLuan.isSelected()){
                hinhThuc = "Tự luận";
            }

            if((!hinhThuc.equals("Tự luận")) && (Validation.isEmpty(txtNDCauHoi.getText()) || Validation.isEmpty(txtLC1.getText()) || Validation.isEmpty(txtLC2.getText())
                || Validation.isEmpty(txtLC3.getText()) || Validation.isEmpty(txtLC4.getText()))){
                showError("Vui lòng điền đầy đủ thông tin !");
            }else if("Tự luận".equals(hinhThuc) && Validation.isEmpty(txtNDCauHoi.getText())){
                showError("Vui lòng điền đầy đủ thông tin !");
            }
            else{
                
                if(cauhoidao.delete(Integer.parseInt(id)) > -1){
                    showMessage("Xóa Bài Khảo Sát thành công !");
                    tableModelCH.removeRow(tableCauHoi.getSelectedRow());
                    resetCauHoi();
                }else{
                    showMessage("Xóa Bài Khảo Sát thất bại !");
                }
            }
        }else{
            if(tableCauHoi.getRowCount() == 0){
                JOptionPane.showMessageDialog(null, "Table hiện đang trống !","Cảnh báo", JOptionPane.WARNING_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng bạn muốn xóa !","Lỗi",JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnXoaCauHoiActionPerformed

    private void tableCauHoiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCauHoiMouseClicked
        String noidung       = tableCauHoi.getValueAt(tableCauHoi.getSelectedRow(), 1).toString();
        String option1       = tableCauHoi.getValueAt(tableCauHoi.getSelectedRow(), 2).toString();
        String option2       = tableCauHoi.getValueAt(tableCauHoi.getSelectedRow(), 3).toString();
        String option3       = tableCauHoi.getValueAt(tableCauHoi.getSelectedRow(),4).toString();
        String option4       = tableCauHoi.getValueAt(tableCauHoi.getSelectedRow(),5).toString();
        String hinhthuc      = tableCauHoi.getValueAt(tableCauHoi.getSelectedRow(), 6).toString();
  
        if(hinhthuc.equals("Tự luận")){
            txtNDCauHoi.setText(noidung);
            txtLC1.setEnabled(false);
            txtLC2.setEnabled(false);
            txtLC3.setEnabled(false);
            txtLC4.setEnabled(false);
        }else{
            txtNDCauHoi.setText(noidung);
            txtLC1.setText(option1);
            txtLC2.setText(option2);
            txtLC3.setText(option3);
            txtLC4.setText(option4);
        }
        
        switch (hinhthuc) {
            case "Đơn lựa chọn" -> rdDonLC.setSelected(true);
            case "Đa lựa chọn"  -> rdDaLC.setSelected(true);
            case "Tự luận"      -> rdTuLuan.setSelected(true);
        }
    }//GEN-LAST:event_tableCauHoiMouseClicked

    private void rdTuLuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTuLuanActionPerformed
        txtLC1.setEnabled(false);
        txtLC2.setEnabled(false);
        txtLC3.setEnabled(false);
        txtLC4.setEnabled(false);
    }//GEN-LAST:event_rdTuLuanActionPerformed

    private void rdDaLCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdDaLCActionPerformed
        txtLC1.setEnabled(true);
        txtLC2.setEnabled(true);
        txtLC3.setEnabled(true);
        txtLC4.setEnabled(true);
    }//GEN-LAST:event_rdDaLCActionPerformed
    
    private void showMessage(String msg){
        JOptionPane.showMessageDialog(null, msg);
    }
    
    private void showError(String msg){
        JOptionPane.showMessageDialog(null, msg,"Lỗi",JOptionPane.ERROR_MESSAGE);
    }

    private void showDoiTuong(List<CapBac> list){
        for(int i = 0 ; i < list.size() ; i++){
            cbDoiTuong.addItem(list.get(i).getTenCapBac());
        }
    }
    
    private void THeaderTable(){
        JTableHeader header = tableBaiKhaoSat.getTableHeader();
        header.setFont(new Font("SansSerif", WIDTH, 14));
    }
    
    private void showDSBaiKhaoSat(){
        THeaderTable();
        tableModelBKS.setRowCount(0);
        List<BaiKhaoSat> list = ksdao.selectBaiKhaoSat();
        if(list != null){
            for (BaiKhaoSat bks : list) {
                Object[] row = new Object[]{
                bks.getId(),bks.getTieuDe(),bks.getDoiTuong(),bks.getThoiGianBatDau(),bks.getThoiGianKetThuc(),bks.getTrangThai()};
                tableModelBKS.addRow(row);
            }
        }
    }
    
    private void showQuestion(List<CauHoi> list){
            JTableHeader header = tableCauHoi.getTableHeader();
            header.setFont(new Font("SansSerif", WIDTH, 14));
            tableModelCH.setRowCount(0);
            if(list != null){
                for (CauHoi cauHoi : list) {
                Object[] row = new Object[]{
                  cauHoi.getId(),cauHoi.getNoiDung(),cauHoi.getLuaChon1(),cauHoi.getLuaChon2(),cauHoi.getLuaChon3(),cauHoi.getLuaChon4(),cauHoi.getHinhThuc()};
                    
                    tableCauHoi.getColumnModel().getColumn(0).setMinWidth(0);
                    tableModelCH.addRow(row);
                }
            }
    }
    
    private List<BaiKhaoSat> searchBKSByDoiTuong(List<BaiKhaoSat> list, String key){
        List<BaiKhaoSat> resultList = new ArrayList<>();
        var regex = ".*" + key + ".*";
        Pattern pattern = Pattern.compile(regex, Pattern.CASE_INSENSITIVE);
        Matcher matcher;
        for (BaiKhaoSat baiKhaoSat : list) {
            matcher = pattern.matcher(baiKhaoSat.getTieuDe());
            if (matcher.matches()) {
                resultList.add(baiKhaoSat);
            }
        }
        return resultList;
    }
    
    private boolean ngayHopLe(Date date){
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String ngay = dateFormat.format(date);
        
        LocalDate dateSS = LocalDate.parse(ngay);
        
        LocalDate dateCur = LocalDate.now();
        if(dateSS.isBefore(dateCur)){
            return false;
        }
        return true;
    }
    
    private void showTimKiem(List<BaiKhaoSat> list){
        THeaderTable();
        tableModelBKS.setRowCount(0);
        if(list != null){
            for (BaiKhaoSat bks : list) {
                Object[] row = new Object[]{
                bks.getId(),bks.getTieuDe(),bks.getDoiTuong(),bks.getThoiGianBatDau(),bks.getThoiGianKetThuc(),bks.getTrangThai()};
                tableModelBKS.addRow(row);
            }
        }
    }
    
    private void reset(){
        cbDoiTuong.setSelectedIndex(0);
        txtTieuDe.setText("");
        cbTrangThai.setSelectedIndex(0);
        dateStart.setCalendar(null);
        dateEnd.setCalendar(null);
    }
    
    private void resetCauHoi(){
        txtNDCauHoi.setText("");
        txtLC1.setText("");
        txtLC2.setText("");
        txtLC3.setText("");
        txtLC4.setText("");
        btnGroupHinhThucLC.clearSelection();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DonLuaChon;
    private javax.swing.JPanel JCauHoi;
    private javax.swing.JPanel JContainer;
    private javax.swing.JPanel LuaChon;
    private javax.swing.JButton btnCapNhatCauHoi;
    private javax.swing.JButton btnChiTiet;
    private javax.swing.ButtonGroup btnGroupFilter;
    private javax.swing.ButtonGroup btnGroupHinhThucLC;
    private javax.swing.JButton btnHuyTimKiem;
    private javax.swing.JButton btnImportExecel1;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThemCauHoi;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaCauHoi;
    private javax.swing.JComboBox<String> cbDoiTuong;
    private javax.swing.JComboBox<String> cbTrangThai;
    private com.toedter.calendar.JDateChooser dateEnd;
    private com.toedter.calendar.JDateChooser dateStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JRadioButton rdDaLC;
    private javax.swing.JRadioButton rdDonLC;
    private javax.swing.JRadioButton rdTenDeThi;
    private javax.swing.JRadioButton rdThoiGianGiamDan;
    private javax.swing.JRadioButton rdThoiGianTangDan;
    private javax.swing.JRadioButton rdTuLuan;
    private javax.swing.JTable tableBaiKhaoSat;
    private javax.swing.JTable tableCauHoi;
    private javax.swing.JTextField txtLC1;
    private javax.swing.JTextField txtLC2;
    private javax.swing.JTextField txtLC3;
    private javax.swing.JTextField txtLC4;
    private javax.swing.JTextArea txtNDCauHoi;
    private javax.swing.JTextField txtTenDe;
    private javax.swing.JTextArea txtTieuDe;
    // End of variables declaration//GEN-END:variables

    
}
