/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Admin;

import DAO.KhaoSatDAO;
import DAO.QuanNhanDAO;
import Model.BaiKhaoSat;
import Model.CapBac;
import Model.CauHoi;
import Model.DonVi;
import Model.PhanHoi;
import Model.QuanNhan;
import Model.ThongKe;
import Utils.CenteredHeaderRenderer;
import Utils.CenteredTableCellRenderer;
import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Panel;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.print.attribute.HashPrintRequestAttributeSet;
import javax.print.attribute.PrintRequestAttribute;
import javax.print.attribute.PrintRequestAttributeSet;
import javax.print.attribute.standard.OrientationRequested;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.labels.StandardPieSectionLabelGenerator;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PiePlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.LineAndShapeRenderer;
import org.jfree.data.category.DefaultCategoryDataset;
import org.jfree.data.general.DefaultPieDataset;

/**
 *
 * @author DELL
 */
public class QuanLyThongKe extends javax.swing.JPanel {
    QuanNhanDAO qndao = new QuanNhanDAO();
    KhaoSatDAO ksdao = new KhaoSatDAO();
    DefaultTableModel tableModel = new DefaultTableModel();
    DefaultTableModel tableModelPhanHoi = new DefaultTableModel();
    DefaultTableModel tableModelNguoiThamGia = new DefaultTableModel();
    DefaultTableModel tableModelChiTietTraLoi = new DefaultTableModel();
    DefaultTableModel tableModelTkSoLuongTraLoi = new DefaultTableModel();
    
    
    static int idBKS = -1;
    int idQN = -1;
    
    CauHoi cauHoiTK_SoLuong = null;
    CauHoi cauHoiTK_DuLieu  = null;
    /**
     * Creates new form ManagerThongKe
     */
    public QuanLyThongKe() {
        initComponents();
        tableModel = (DefaultTableModel) tableThongKe.getModel();
        tableModelPhanHoi = (DefaultTableModel) tablePhanHoi.getModel();
        tableModelNguoiThamGia = (DefaultTableModel) tableNguoiThamGia.getModel();
        tableModelChiTietTraLoi = (DefaultTableModel) tableChiTietTraLoi.getModel();
        tableModelTkSoLuongTraLoi = (DefaultTableModel) table_TKLuaChonDapAn.getModel();
        JThongKeTongQuat.setVisible(true);
        jChiTietNguoiThamGia.setVisible(false);
        jChiTietTraLoi.setVisible(false);
        jChiTietPhanHoi.setVisible(false);
        jBieuDoThongKe.setVisible(false);
        jThongKeLuaChonDapAn.setVisible(false);
        showThongKeTongQuat();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupFilterSort = new javax.swing.ButtonGroup();
        btnGroupFilterPhanHoi = new javax.swing.ButtonGroup();
        btnGroupNguoiThamGia = new javax.swing.ButtonGroup();
        ThongKeMain = new javax.swing.JPanel();
        JThongKeTongQuat = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableThongKe = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        rdSortAscByNguoiThamGia = new javax.swing.JRadioButton();
        rdSortDescByPhanHoi = new javax.swing.JRadioButton();
        rdTKTenBKS = new javax.swing.JRadioButton();
        btnTimKiem = new javax.swing.JButton();
        btnHuyTimKiem = new javax.swing.JButton();
        txtFilterNameBKS = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnChiTietThamGia = new javax.swing.JButton();
        btnXuatFile = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnChiTietPhanHoi = new javax.swing.JButton();
        btnTKSoLuongTraLoi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jChiTietNguoiThamGia = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnBackTongQuat = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        btnChiTietTraLoi = new javax.swing.JButton();
        btnHuyTKNguoiThamGia = new javax.swing.JButton();
        btnTKNguoiThamGia = new javax.swing.JButton();
        rdTKTenTK = new javax.swing.JRadioButton();
        rdTKTenQN = new javax.swing.JRadioButton();
        txtTKNguoiThamGia = new javax.swing.JTextField();
        rdTKCapBac = new javax.swing.JRadioButton();
        cbTKCapBac = new javax.swing.JComboBox<>();
        rdTKDonVi = new javax.swing.JRadioButton();
        cbTKDonVi = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableNguoiThamGia = new javax.swing.JTable();
        jChiTietTraLoi = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        btnBackNguoiThamGia = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableChiTietTraLoi = new javax.swing.JTable();
        jChiTietPhanHoi = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnBackTQ = new javax.swing.JButton();
        rdTKTenQNPhanHoi = new javax.swing.JRadioButton();
        rdTKCmndPhanHoi = new javax.swing.JRadioButton();
        rdSXThoiGianPhanHoi = new javax.swing.JRadioButton();
        txtTKPhanHoi = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablePhanHoi = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        btnTKPhanHoi = new javax.swing.JButton();
        btnHuyTKPhanHoi = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jBieuDoThongKe = new javax.swing.JPanel();
        btnQLTKTQ = new javax.swing.JButton();
        jpnView1 = new javax.swing.JPanel();
        jpnView2 = new javax.swing.JPanel();
        jThongKeLuaChonDapAn = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btn_QuayLaiNguoiThamGia = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_TKLuaChonDapAn = new javax.swing.JTable();
        BieuDoTKTraLoi = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jViewBieuDoTraLoi = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(980, 590));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ThongKeMain.setLayout(new java.awt.CardLayout());

        JThongKeTongQuat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(0, 0, 51));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("THỐNG KÊ BÀI KHẢO SÁT");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(375, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        JThongKeTongQuat.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 40));

        tableThongKe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tableThongKe.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Bài Khảo Sát", "Bắt Đầu", "Kết Thúc", "Số Câu Hỏi", "Số Người Tham Gia", "Số Lượng Phản Hồi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableThongKe.setRowHeight(50);
        tableThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableThongKeMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tableThongKe);
        if (tableThongKe.getColumnModel().getColumnCount() > 0) {
            tableThongKe.getColumnModel().getColumn(0).setMaxWidth(50);
            tableThongKe.getColumnModel().getColumn(1).setMinWidth(300);
            tableThongKe.getColumnModel().getColumn(3).setMinWidth(30);
        }

        JThongKeTongQuat.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 1110, 360));
        jScrollPane5.getAccessibleContext().setAccessibleDescription("");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Bộ lọc theo Điểm & Kết Quả"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnGroupFilterSort.add(rdSortAscByNguoiThamGia);
        rdSortAscByNguoiThamGia.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        rdSortAscByNguoiThamGia.setForeground(new java.awt.Color(255, 255, 255));
        rdSortAscByNguoiThamGia.setText("Sắp Xếp Tăng Dần Theo Số Người Tham Gia Khảo Sát");
        rdSortAscByNguoiThamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSortAscByNguoiThamGiaActionPerformed(evt);
            }
        });
        jPanel2.add(rdSortAscByNguoiThamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 18, 366, -1));

        btnGroupFilterSort.add(rdSortDescByPhanHoi);
        rdSortDescByPhanHoi.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        rdSortDescByPhanHoi.setForeground(new java.awt.Color(255, 255, 255));
        rdSortDescByPhanHoi.setText("Sắp Xếp Tăng Dần Theo Số Lượng Phản Hồi Bài Khảo Sát");
        rdSortDescByPhanHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSortDescByPhanHoiActionPerformed(evt);
            }
        });
        jPanel2.add(rdSortDescByPhanHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 53, -1, -1));

        btnGroupFilterSort.add(rdTKTenBKS);
        rdTKTenBKS.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        rdTKTenBKS.setForeground(new java.awt.Color(255, 255, 255));
        rdTKTenBKS.setText("Tìm Kiếm theo tên Bài Khảo Sát");
        rdTKTenBKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdTKTenBKSActionPerformed(evt);
            }
        });
        jPanel2.add(rdTKTenBKS, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 88, 366, -1));

        btnTimKiem.setBackground(new java.awt.Color(0, 153, 153));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 0));
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel2.add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 11, 120, 40));

        btnHuyTimKiem.setBackground(new java.awt.Color(204, 51, 0));
        btnHuyTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnHuyTimKiem.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyTimKiem.setText("Hủy Tìm Kiếm");
        btnHuyTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyTimKiemActionPerformed(evt);
            }
        });
        jPanel2.add(btnHuyTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(456, 69, 120, 40));
        jPanel2.add(txtFilterNameBKS, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 129, 344, 35));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (1).jpg"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 590, 180));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 590, 176));

        btnChiTietThamGia.setBackground(new java.awt.Color(102, 204, 0));
        btnChiTietThamGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTietThamGia.setForeground(new java.awt.Color(0, 0, 51));
        btnChiTietThamGia.setText("Xem Chi Tiết Người Tham Gia");
        btnChiTietThamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietThamGiaActionPerformed(evt);
            }
        });
        jPanel1.add(btnChiTietThamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(872, 77, -1, 50));

        btnXuatFile.setBackground(new java.awt.Color(0, 204, 153));
        btnXuatFile.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXuatFile.setText("Xuất File");
        btnXuatFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatFileActionPerformed(evt);
            }
        });
        jPanel1.add(btnXuatFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(872, 6, 232, 53));

        btnThongKe.setBackground(new java.awt.Color(102, 0, 102));
        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThongKe.setForeground(new java.awt.Color(255, 255, 0));
        btnThongKe.setText("Biểu Đồ Thống Kê Tổng Quát");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });
        jPanel1.add(btnThongKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 6, 240, 53));

        btnChiTietPhanHoi.setBackground(new java.awt.Color(255, 102, 0));
        btnChiTietPhanHoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTietPhanHoi.setText("Xem Chi Tiết Các Phản Hồi");
        btnChiTietPhanHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietPhanHoiActionPerformed(evt);
            }
        });
        jPanel1.add(btnChiTietPhanHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 77, 240, 50));

        btnTKSoLuongTraLoi.setBackground(new java.awt.Color(255, 255, 0));
        btnTKSoLuongTraLoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTKSoLuongTraLoi.setText("Thống Kê Số Lượng Trả Lời");
        btnTKSoLuongTraLoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKSoLuongTraLoiActionPerformed(evt);
            }
        });
        jPanel1.add(btnTKSoLuongTraLoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 140, 240, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (2).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -4, 1110, 200));

        JThongKeTongQuat.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1110, 200));

        ThongKeMain.add(JThongKeTongQuat, "TKTongQuat");

        jChiTietNguoiThamGia.setBackground(new java.awt.Color(204, 204, 255));
        jChiTietNguoiThamGia.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackTongQuat.setBackground(new java.awt.Color(153, 51, 0));
        btnBackTongQuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackTongQuat.setForeground(new java.awt.Color(255, 255, 255));
        btnBackTongQuat.setText("Quay Lại");
        btnBackTongQuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackTongQuatActionPerformed(evt);
            }
        });
        jPanel4.add(btnBackTongQuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 9, 92, 40));

        btnChiTietTraLoi.setBackground(new java.awt.Color(51, 204, 0));
        btnChiTietTraLoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnChiTietTraLoi.setForeground(new java.awt.Color(255, 255, 0));
        btnChiTietTraLoi.setText("Xem Chi Tiết Khảo Sát");
        btnChiTietTraLoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChiTietTraLoiActionPerformed(evt);
            }
        });

        btnHuyTKNguoiThamGia.setBackground(new java.awt.Color(255, 102, 0));
        btnHuyTKNguoiThamGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuyTKNguoiThamGia.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyTKNguoiThamGia.setText("Hủy tìm kiếm");
        btnHuyTKNguoiThamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyTKNguoiThamGiaActionPerformed(evt);
            }
        });

        btnTKNguoiThamGia.setBackground(new java.awt.Color(0, 102, 102));
        btnTKNguoiThamGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTKNguoiThamGia.setForeground(new java.awt.Color(255, 255, 255));
        btnTKNguoiThamGia.setText("Tìm kiếm");
        btnTKNguoiThamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKNguoiThamGiaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHuyTKNguoiThamGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(btnChiTietTraLoi)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnTKNguoiThamGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTKNguoiThamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHuyTKNguoiThamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnChiTietTraLoi, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(911, 6, -1, -1));

        btnGroupNguoiThamGia.add(rdTKTenTK);
        rdTKTenTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdTKTenTK.setForeground(new java.awt.Color(255, 255, 255));
        rdTKTenTK.setText("Tìm kiếm theo tên Tài Khoản");
        jPanel4.add(rdTKTenTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 6, 229, 33));

        btnGroupNguoiThamGia.add(rdTKTenQN);
        rdTKTenQN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdTKTenQN.setForeground(new java.awt.Color(255, 255, 255));
        rdTKTenQN.setText("Tìm kiếm theo tên Quân Nhân");
        jPanel4.add(rdTKTenQN, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 58, -1, 33));

        txtTKNguoiThamGia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(txtTKNguoiThamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(664, 109, 229, 32));

        btnGroupNguoiThamGia.add(rdTKCapBac);
        rdTKCapBac.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdTKCapBac.setForeground(new java.awt.Color(255, 255, 255));
        rdTKCapBac.setText("Tìm kiếm theo cấp bậc");
        jPanel4.add(rdTKCapBac, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 10, 207, -1));

        cbTKCapBac.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(cbTKCapBac, new org.netbeans.lib.awtextra.AbsoluteConstraints(439, 58, 207, 31));

        btnGroupNguoiThamGia.add(rdTKDonVi);
        rdTKDonVi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdTKDonVi.setForeground(new java.awt.Color(255, 255, 255));
        rdTKDonVi.setText("Tìm kiếm theo đơn vị");
        jPanel4.add(rdTKDonVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 6, 186, 34));

        jPanel4.add(cbTKDonVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 58, 186, 31));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (2).jpg"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 150));

        jChiTietNguoiThamGia.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 150));

        tableNguoiThamGia.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        tableNguoiThamGia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên tài khoản", "Số CMND", "Tên Quân Nhân", "Ngày sinh", "Cấp Bậc", "Đơn Vị"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableNguoiThamGia.setRowHeight(50);
        tableNguoiThamGia.setShowGrid(false);
        tableNguoiThamGia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableNguoiThamGiaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableNguoiThamGia);

        jChiTietNguoiThamGia.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 1110, 410));

        ThongKeMain.add(jChiTietNguoiThamGia, "TKNguoiThamGia");

        jChiTietTraLoi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackNguoiThamGia.setBackground(new java.awt.Color(102, 0, 0));
        btnBackNguoiThamGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackNguoiThamGia.setForeground(new java.awt.Color(255, 255, 255));
        btnBackNguoiThamGia.setText("Quay Lại");
        btnBackNguoiThamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackNguoiThamGiaActionPerformed(evt);
            }
        });
        jPanel3.add(btnBackNguoiThamGia, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 110, 44));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (2).jpg"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 70));

        jChiTietTraLoi.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 70));

        tableChiTietTraLoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Nội dung câu hỏi", "Lựa chọn 1", "Lựa chọn 2", "Lựa chọn 3", "Lựa chọn 4", "Hình Thức", "Câu trả lời"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableChiTietTraLoi.setRowHeight(50);
        jScrollPane1.setViewportView(tableChiTietTraLoi);
        if (tableChiTietTraLoi.getColumnModel().getColumnCount() > 0) {
            tableChiTietTraLoi.getColumnModel().getColumn(5).setMinWidth(200);
            tableChiTietTraLoi.getColumnModel().getColumn(6).setMinWidth(200);
        }

        jChiTietTraLoi.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1120, 530));

        ThongKeMain.add(jChiTietTraLoi, "TKChiTietTraLoi");

        jChiTietPhanHoi.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBackTQ.setBackground(new java.awt.Color(102, 0, 0));
        btnBackTQ.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBackTQ.setForeground(new java.awt.Color(255, 255, 255));
        btnBackTQ.setText("Quay Lại");
        btnBackTQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackTQActionPerformed(evt);
            }
        });
        jPanel5.add(btnBackTQ, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 99, 35));

        btnGroupFilterPhanHoi.add(rdTKTenQNPhanHoi);
        rdTKTenQNPhanHoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdTKTenQNPhanHoi.setForeground(new java.awt.Color(255, 255, 255));
        rdTKTenQNPhanHoi.setText("Tìm kiếm theo tên Quân Nhân");
        jPanel5.add(rdTKTenQNPhanHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 10, 277, 33));

        btnGroupFilterPhanHoi.add(rdTKCmndPhanHoi);
        rdTKCmndPhanHoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdTKCmndPhanHoi.setForeground(new java.awt.Color(255, 255, 255));
        rdTKCmndPhanHoi.setText("Tìm kiếm theo số CMND");
        jPanel5.add(rdTKCmndPhanHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 40, 277, 35));

        btnGroupFilterPhanHoi.add(rdSXThoiGianPhanHoi);
        rdSXThoiGianPhanHoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdSXThoiGianPhanHoi.setForeground(new java.awt.Color(255, 255, 255));
        rdSXThoiGianPhanHoi.setText("Sắp xếp theo thời gian phản hồi");
        rdSXThoiGianPhanHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdSXThoiGianPhanHoiActionPerformed(evt);
            }
        });
        jPanel5.add(rdSXThoiGianPhanHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 247, 33));

        txtTKPhanHoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel5.add(txtTKPhanHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 90, 277, 34));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (1) (1).jpg"))); // NOI18N
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 130));

        jChiTietPhanHoi.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 960, 130));

        tablePhanHoi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên Bài Khảo Sát", "Tên Quân Nhân", "Số CMND", "Nội dung phản hồi", "Thời gian phản hồi"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablePhanHoi.setRowHeight(60);
        jScrollPane3.setViewportView(tablePhanHoi);
        if (tablePhanHoi.getColumnModel().getColumnCount() > 0) {
            tablePhanHoi.getColumnModel().getColumn(0).setMinWidth(250);
            tablePhanHoi.getColumnModel().getColumn(1).setMinWidth(200);
            tablePhanHoi.getColumnModel().getColumn(3).setMinWidth(190);
        }

        jChiTietPhanHoi.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 1110, 480));

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTKPhanHoi.setBackground(new java.awt.Color(0, 102, 102));
        btnTKPhanHoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTKPhanHoi.setForeground(new java.awt.Color(255, 255, 255));
        btnTKPhanHoi.setText("Tìm kiếm");
        btnTKPhanHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTKPhanHoiActionPerformed(evt);
            }
        });
        jPanel6.add(btnTKPhanHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 140, 38));

        btnHuyTKPhanHoi.setBackground(new java.awt.Color(255, 51, 0));
        btnHuyTKPhanHoi.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnHuyTKPhanHoi.setForeground(new java.awt.Color(255, 255, 255));
        btnHuyTKPhanHoi.setText("Hủy tìm kiếm");
        btnHuyTKPhanHoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyTKPhanHoiActionPerformed(evt);
            }
        });
        jPanel6.add(btnHuyTKPhanHoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 91, 140, 33));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (1).jpg"))); // NOI18N
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 130));

        jChiTietPhanHoi.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 0, -1, 130));

        ThongKeMain.add(jChiTietPhanHoi, "TKPhanHoi");

        btnQLTKTQ.setBackground(new java.awt.Color(153, 0, 0));
        btnQLTKTQ.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQLTKTQ.setForeground(new java.awt.Color(255, 255, 255));
        btnQLTKTQ.setText("Quay lại");
        btnQLTKTQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLTKTQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnView1Layout = new javax.swing.GroupLayout(jpnView1);
        jpnView1.setLayout(jpnView1Layout);
        jpnView1Layout.setHorizontalGroup(
            jpnView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnView1Layout.setVerticalGroup(
            jpnView1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnView2Layout = new javax.swing.GroupLayout(jpnView2);
        jpnView2.setLayout(jpnView2Layout);
        jpnView2Layout.setHorizontalGroup(
            jpnView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jpnView2Layout.setVerticalGroup(
            jpnView2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jBieuDoThongKeLayout = new javax.swing.GroupLayout(jBieuDoThongKe);
        jBieuDoThongKe.setLayout(jBieuDoThongKeLayout);
        jBieuDoThongKeLayout.setHorizontalGroup(
            jBieuDoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBieuDoThongKeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jBieuDoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnView1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jBieuDoThongKeLayout.createSequentialGroup()
                        .addComponent(btnQLTKTQ, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1002, Short.MAX_VALUE))
                    .addComponent(jpnView2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jBieuDoThongKeLayout.setVerticalGroup(
            jBieuDoThongKeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBieuDoThongKeLayout.createSequentialGroup()
                .addComponent(btnQLTKTQ, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnView2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        ThongKeMain.add(jBieuDoThongKe, "TKBieuDo");

        jThongKeLuaChonDapAn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_QuayLaiNguoiThamGia.setBackground(new java.awt.Color(102, 0, 0));
        btn_QuayLaiNguoiThamGia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_QuayLaiNguoiThamGia.setForeground(new java.awt.Color(255, 255, 255));
        btn_QuayLaiNguoiThamGia.setText("Quay Lại");
        btn_QuayLaiNguoiThamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_QuayLaiNguoiThamGiaActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(255, 255, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setText("Thống Kê dạng Biểu Đồ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_QuayLaiNguoiThamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 780, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_QuayLaiNguoiThamGia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jThongKeLuaChonDapAn.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1100, 80));

        table_TKLuaChonDapAn.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        table_TKLuaChonDapAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nội dung câu hỏi", "Số lượng trả lời", "Số lượng trả lời", "Số lượng trả lời", "Số lượng trả lời"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_TKLuaChonDapAn.setRowHeight(50);
        table_TKLuaChonDapAn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_TKLuaChonDapAnMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_TKLuaChonDapAn);
        if (table_TKLuaChonDapAn.getColumnModel().getColumnCount() > 0) {
            table_TKLuaChonDapAn.getColumnModel().getColumn(0).setMaxWidth(0);
            table_TKLuaChonDapAn.getColumnModel().getColumn(1).setMinWidth(250);
        }

        jThongKeLuaChonDapAn.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 77, 1100, 530));

        ThongKeMain.add(jThongKeLuaChonDapAn, "TKSoLuongTraLoi");

        jButton2.setBackground(new java.awt.Color(102, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Quay lại");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1004, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jViewBieuDoTraLoiLayout = new javax.swing.GroupLayout(jViewBieuDoTraLoi);
        jViewBieuDoTraLoi.setLayout(jViewBieuDoTraLoiLayout);
        jViewBieuDoTraLoiLayout.setHorizontalGroup(
            jViewBieuDoTraLoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jViewBieuDoTraLoiLayout.setVerticalGroup(
            jViewBieuDoTraLoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 341, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout BieuDoTKTraLoiLayout = new javax.swing.GroupLayout(BieuDoTKTraLoi);
        BieuDoTKTraLoi.setLayout(BieuDoTKTraLoiLayout);
        BieuDoTKTraLoiLayout.setHorizontalGroup(
            BieuDoTKTraLoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jViewBieuDoTraLoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BieuDoTKTraLoiLayout.setVerticalGroup(
            BieuDoTKTraLoiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BieuDoTKTraLoiLayout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jViewBieuDoTraLoi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 207, Short.MAX_VALUE))
        );

        ThongKeMain.add(BieuDoTKTraLoi, "BieuDoTKTraLoi");

        add(ThongKeMain, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 620));
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackTongQuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackTongQuatActionPerformed
        CardLayout cardLayout = (CardLayout) ThongKeMain.getLayout();
        cardLayout.show(ThongKeMain, "TKTongQuat");
        showThongKeTongQuat();
        
    }//GEN-LAST:event_btnBackTongQuatActionPerformed

    private void btnChiTietThamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietThamGiaActionPerformed
        if(tableThongKe.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng muốn xem chi tiết", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }else{
            CardLayout cardLayout = (CardLayout) ThongKeMain.getLayout();
            cardLayout.show(ThongKeMain, "TKNguoiThamGia");
            showNguoiThamGia();
            showCapBac(ksdao.selectCapBac());
            showDonVi(qndao.selectDonVi());
        }
        
    }//GEN-LAST:event_btnChiTietThamGiaActionPerformed

    private void btnChiTietPhanHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietPhanHoiActionPerformed
        
        if(tableThongKe.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng muốn xem chi tiết", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }else{
            CardLayout cardLayout = (CardLayout) ThongKeMain.getLayout();
            cardLayout.show(ThongKeMain, "TKPhanHoi");
            showPhanHoi();
        }

    }//GEN-LAST:event_btnChiTietPhanHoiActionPerformed

    private void btnChiTietTraLoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChiTietTraLoiActionPerformed
        
        if(tableNguoiThamGia.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn hàng muốn xem chi tiết", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
        else{
            CardLayout cardLayout = (CardLayout) ThongKeMain.getLayout();
            cardLayout.show(ThongKeMain, "TKChiTietTraLoi");
            showChiTietTraLoi();
        }

    }//GEN-LAST:event_btnChiTietTraLoiActionPerformed

    private void btnBackTQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackTQActionPerformed
          CardLayout cardLayout = (CardLayout) ThongKeMain.getLayout();
          cardLayout.show(ThongKeMain, "TKTongQuat");
          showThongKeTongQuat();
 
    }//GEN-LAST:event_btnBackTQActionPerformed

    private void btnBackNguoiThamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackNguoiThamGiaActionPerformed
        CardLayout cardLayout = (CardLayout) ThongKeMain.getLayout();
        cardLayout.show(ThongKeMain, "TKNguoiThamGia");
        showNguoiThamGia();
    }//GEN-LAST:event_btnBackNguoiThamGiaActionPerformed

    private void tableThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableThongKeMouseClicked
        idBKS = Integer.parseInt(tableThongKe.getValueAt(tableThongKe.getSelectedRow(), 0).toString());
        System.out.println("id bks mouse click "+ idBKS);
    }//GEN-LAST:event_tableThongKeMouseClicked

    private void tableNguoiThamGiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableNguoiThamGiaMouseClicked
        idQN = Integer.parseInt(tableNguoiThamGia.getValueAt(tableNguoiThamGia.getSelectedRow(), 0).toString());
        System.out.println("id QN mouse click "+ idQN);
    }//GEN-LAST:event_tableNguoiThamGiaMouseClicked

    private void btnXuatFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatFileActionPerformed
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd-MM-yyyy");
        String date = formatter.format(java.time.LocalDate.now());
       
        MessageFormat header=new MessageFormat("Report From "+date);
        MessageFormat footer=new MessageFormat("page{0,number,integer}");
        try {
            tableThongKe.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (PrinterException e) {
            e.getMessage();
        } 
    }//GEN-LAST:event_btnXuatFileActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        CardLayout cardLayout = (CardLayout) ThongKeMain.getLayout();
        cardLayout.show(ThongKeMain, "TKBieuDo");
        setDataChart01(jpnView1);
        setDataChart02(jpnView2);
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnQLTKTQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLTKTQActionPerformed
        CardLayout cardLayout = (CardLayout) ThongKeMain.getLayout();
        cardLayout.show(ThongKeMain, "TKTongQuat");
    }//GEN-LAST:event_btnQLTKTQActionPerformed

    private void rdSortAscByNguoiThamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSortAscByNguoiThamGiaActionPerformed
        btnTimKiem.setEnabled(false);
        List<BaiKhaoSat> list = ksdao.thongkeTongQuat();
        Collections.sort(list, (BaiKhaoSat o1, BaiKhaoSat o2) -> o1.getSoLuongQN() - o2.getSoLuongQN());
        tableModel.setRowCount(0);
        showTimKiemTongQuat(list);
    }//GEN-LAST:event_rdSortAscByNguoiThamGiaActionPerformed

    private void rdSortDescByPhanHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSortDescByPhanHoiActionPerformed
        btnTimKiem.setEnabled(false);
        List<BaiKhaoSat> list = ksdao.thongkeTongQuat();
        Collections.sort(list, (BaiKhaoSat o1, BaiKhaoSat o2) -> o1.getSoLuongPH()- o2.getSoLuongPH());
        tableModel.setRowCount(0);
        showTimKiemTongQuat(list);
    }//GEN-LAST:event_rdSortDescByPhanHoiActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        if(rdTKTenBKS.isSelected()){
            String key = txtFilterNameBKS.getText();
            List<BaiKhaoSat> list = ksdao.thongkeTongQuat();
            if (key.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập tên Bài Khảo Sát cần tìm kiếm!");
            } else {
                List<BaiKhaoSat> listResult = searchBKSByName(list, key);
                tableModel.setRowCount(0);
                showTimKiemTongQuat(listResult);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng lựa chọn hình thức tìm kiếm");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnHuyTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyTimKiemActionPerformed
        btnTimKiem.setEnabled(true);
        txtFilterNameBKS.setText("");
        btnGroupFilterSort.clearSelection();
        tableModel.setRowCount(0);
        showThongKeTongQuat();
    }//GEN-LAST:event_btnHuyTimKiemActionPerformed

    private void rdSXThoiGianPhanHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdSXThoiGianPhanHoiActionPerformed
       btnTKPhanHoi.setEnabled(false);
       List<PhanHoi> list = ksdao.ThongKePhanHoi(idBKS);
       Collections.sort(list, new Comparator<PhanHoi>(){
           @Override
           public int compare(PhanHoi o1, PhanHoi o2) {
               return o2.getThoiGian().compareTo(o1.getThoiGian());
           }
       });
       tableModelPhanHoi.setRowCount(0);
       showTimKiemPhanHoi(list);
    }//GEN-LAST:event_rdSXThoiGianPhanHoiActionPerformed

    private void btnTKPhanHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKPhanHoiActionPerformed
        List<PhanHoi> list = ksdao.ThongKePhanHoi(idBKS);
        String key = txtTKPhanHoi.getText();
        if(rdTKTenQNPhanHoi.isSelected()){
            if(key.isEmpty()){
                JOptionPane.showMessageDialog(null, "Vui lòng nhập tên Quân Nhân tìm kiếm","Cảnh báo",JOptionPane.WARNING_MESSAGE);
            }else{
                List<PhanHoi> listResult = searchNameQNOfPhanhoi(list, key);
                tableModelPhanHoi.setRowCount(0);
                showTimKiemPhanHoi(listResult);
            }
        }
        else if(rdTKCmndPhanHoi.isSelected()){
            if(key.isEmpty()){
                JOptionPane.showMessageDialog(null, "Vui lòng nhập số CMND cần tìm kiếm","Cảnh báo",JOptionPane.WARNING_MESSAGE);
            }else{
               List<PhanHoi> listResult = searchCmndOfPhanhoi(list, key);
                tableModelPhanHoi.setRowCount(0);
                showTimKiemPhanHoi(listResult);
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Vui lòng lựa chọn hình thức tìm kiếm","Cảnh báo",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnTKPhanHoiActionPerformed

    private void btnHuyTKPhanHoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyTKPhanHoiActionPerformed
        btnTKPhanHoi.setEnabled(true);
        txtTKPhanHoi.setText("");
        btnGroupFilterPhanHoi.clearSelection();
        tableModelPhanHoi.setRowCount(0);
        showPhanHoi();
    }//GEN-LAST:event_btnHuyTKPhanHoiActionPerformed

    private void btnTKNguoiThamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKNguoiThamGiaActionPerformed
        List<QuanNhan> list = ksdao.ThongKeNguoiThamGia(idBKS);
        if(rdTKCapBac.isSelected()){
            String key = cbTKCapBac.getItemAt(cbTKCapBac.getSelectedIndex());
            List<QuanNhan> listResult = searchCapBac(list, key);
            tableModelNguoiThamGia.setRowCount(0);
            showTimKiemNguoiThamGia(listResult);
        }
        else if(rdTKDonVi.isSelected()){
            String key = cbTKDonVi.getItemAt(cbTKDonVi.getSelectedIndex());
            List<QuanNhan> listResult = searchDonVi(list, key);
            tableModelNguoiThamGia.setRowCount(0);
            showTimKiemNguoiThamGia(listResult);
        }
        else if(rdTKTenQN.isSelected()){
            String key = txtTKNguoiThamGia.getText();
            if(key.isEmpty()){
                JOptionPane.showMessageDialog(null, "Vui lòng nhập tên Quân Nhân tìm kiếm","Cảnh báo",JOptionPane.WARNING_MESSAGE);
            }else{
                List<QuanNhan> listResult = searchTenQN(list, key);
                tableModelNguoiThamGia.setRowCount(0);
                showTimKiemNguoiThamGia(listResult);
            }
        }
        else if(rdTKTenTK.isSelected()){
            String key = txtTKNguoiThamGia.getText();
            if(key.isEmpty()){
                JOptionPane.showMessageDialog(null, "Vui lòng nhập tên Tài Khoản tìm kiếm","Cảnh báo",JOptionPane.WARNING_MESSAGE);
            }else{
                List<QuanNhan> listResult = searchTenTK(list, key);
                tableModelNguoiThamGia.setRowCount(0);
                showTimKiemNguoiThamGia(listResult);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng lựa chọn hình thức tìm kiếm","Cảnh báo",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnTKNguoiThamGiaActionPerformed

    private void btnHuyTKNguoiThamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyTKNguoiThamGiaActionPerformed
        txtTKNguoiThamGia.setText("");
        btnGroupNguoiThamGia.clearSelection();
        tableModelNguoiThamGia.setRowCount(0);
        showNguoiThamGia();
    }//GEN-LAST:event_btnHuyTKNguoiThamGiaActionPerformed

    private void rdTKTenBKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdTKTenBKSActionPerformed
        btnTimKiem.setEnabled(true);
    }//GEN-LAST:event_rdTKTenBKSActionPerformed

    private void btnTKSoLuongTraLoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTKSoLuongTraLoiActionPerformed
        if(tableThongKe.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn bài khảo sát muốn xem thống kê", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }else{
            CardLayout cardLayout = (CardLayout) ThongKeMain.getLayout();
            cardLayout.show(ThongKeMain, "TKSoLuongTraLoi");
            showSoLuongTraLoi();
        }
    }//GEN-LAST:event_btnTKSoLuongTraLoiActionPerformed

    private void btn_QuayLaiNguoiThamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_QuayLaiNguoiThamGiaActionPerformed
        CardLayout cardLayout = (CardLayout) ThongKeMain.getLayout();
        cardLayout.show(ThongKeMain, "TKTongQuat");
        showThongKeTongQuat();
    }//GEN-LAST:event_btn_QuayLaiNguoiThamGiaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(table_TKLuaChonDapAn.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn câu hỏi muốn xem thống kê", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }else{
            CardLayout cardLayout = (CardLayout) ThongKeMain.getLayout();
            cardLayout.show(ThongKeMain, "BieuDoTKTraLoi");
            setDataChart03(jViewBieuDoTraLoi);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        CardLayout cardLayout = (CardLayout) ThongKeMain.getLayout();
        cardLayout.show(ThongKeMain, "TKSoLuongTraLoi");
        showSoLuongTraLoi();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void table_TKLuaChonDapAnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_TKLuaChonDapAnMouseClicked
        int id = Integer.parseInt(table_TKLuaChonDapAn.getValueAt(table_TKLuaChonDapAn.getSelectedRow(), 0).toString());
        List<CauHoi> listSLTraLoi = ksdao.ThongKeSoLuongTraLoi(idBKS);
        List<CauHoi> list = ksdao.selectCauHoiOfBKS(idBKS);
        for (int i = 0 ; i < list.size() ; i++) {
            if(list.get(i).getId() == id){
                cauHoiTK_DuLieu = list.get(i);
                cauHoiTK_SoLuong = listSLTraLoi.get(i);
                break;
            }
        }
    }//GEN-LAST:event_table_TKLuaChonDapAnMouseClicked

    private List<BaiKhaoSat> searchBKSByName(List<BaiKhaoSat> list, String key){
        List<BaiKhaoSat> resultList = new ArrayList<>();
        var regex = ".*" + key + ".*";
        Pattern pattern = Pattern.compile(regex, Pattern.CASE_INSENSITIVE);
        Matcher matcher;
        for (BaiKhaoSat baiKhaoSat : list) {
            matcher = pattern.matcher(baiKhaoSat.getTieuDe());
            if (matcher.matches()) {
                resultList.add(baiKhaoSat);
            }
        }
        return resultList;
    }
    
    private List<PhanHoi> searchNameQNOfPhanhoi(List<PhanHoi> list, String key){
        List<PhanHoi> resultList = new ArrayList<>();
        var regex = ".*" + key + ".*";
        Pattern pattern = Pattern.compile(regex, Pattern.CASE_INSENSITIVE);
        Matcher matcher;
        for (PhanHoi phanHoi : list) {
            matcher = pattern.matcher(phanHoi.getHoten());
            if (matcher.matches()) {
                resultList.add(phanHoi);
            }
        }
        return resultList;
    }
    
    private List<PhanHoi> searchCmndOfPhanhoi(List<PhanHoi> list, String key){
        List<PhanHoi> resultList = new ArrayList<>();
        var regex = ".*" + key + ".*";
        Pattern pattern = Pattern.compile(regex, Pattern.CASE_INSENSITIVE);
        Matcher matcher;
        for (PhanHoi phanHoi : list) {
            matcher = pattern.matcher(phanHoi.getCmnd());
            if (matcher.matches()) {
                resultList.add(phanHoi);
            }
        }
        return resultList;
    }
    
    private List<QuanNhan> searchCapBac(List<QuanNhan> list, String key){
        List<QuanNhan> resultList = new ArrayList<>();
        for (QuanNhan quanNhan : list) {
            if(key.equals(quanNhan.getCapBac().getTenCapBac())){
                resultList.add(quanNhan);
            }
        }
        return resultList;
    }
    
    private List<QuanNhan> searchDonVi(List<QuanNhan> list, String key){
        List<QuanNhan> resultList = new ArrayList<>();
        for (QuanNhan quanNhan : list) {
            if(key.equals(quanNhan.getDonVi().getTenDonVi())){
                resultList.add(quanNhan);
            }
        }
        return resultList;
    }
    
    private List<QuanNhan> searchTenTK(List<QuanNhan> list, String key){
        List<QuanNhan> resultList = new ArrayList<>();
        var regex = ".*" + key + ".*";
        Pattern pattern = Pattern.compile(regex, Pattern.CASE_INSENSITIVE);
        Matcher matcher;
        for (QuanNhan quanNhan : list) {
            matcher = pattern.matcher(quanNhan.getTenTaiKhoan());
            if (matcher.matches()) {
                resultList.add(quanNhan);
            }
        }
        return resultList;
    }
    
    private List<QuanNhan> searchTenQN(List<QuanNhan> list, String key){
        List<QuanNhan> resultList = new ArrayList<>();
        var regex = ".*" + key + ".*";
        Pattern pattern = Pattern.compile(regex, Pattern.CASE_INSENSITIVE);
        Matcher matcher;
        for (QuanNhan quanNhan : list) {
            matcher = pattern.matcher(quanNhan.getHoTen());
            if (matcher.matches()) {
                resultList.add(quanNhan);
            }
        }
        return resultList;
    }
    
    private void THeaderTableTKTongQuat(){
        JTableHeader header = tableThongKe.getTableHeader();
        header.setFont(new Font("SansSerif", WIDTH, 14));
    }
    
    private void THeaderTableTKPhanHoi(){
        JTableHeader header = tablePhanHoi.getTableHeader();
        header.setFont(new Font("SansSerif", WIDTH, 14));
    }
    
    private void THeaderTableTKNguoiThamGia(){
        JTableHeader header = tableNguoiThamGia.getTableHeader();
        header.setFont(new Font("SansSerif", WIDTH, 14));
    }
    
    private void THeaderTableTKTraLoi(){
        JTableHeader header = tableChiTietTraLoi.getTableHeader();
        header.setFont(new Font("SansSerif", WIDTH, 14));
    }
    
    private void THeaderTableTKSoLuongTraLoi(){
        JTableHeader header = table_TKLuaChonDapAn.getTableHeader();
        header.setFont(new Font("SansSerif", WIDTH, 16));
//        table_TKLuaChonDapAn.getTableHeader().setDefaultRenderer(new CenteredHeaderRenderer());
    }
    
    
    
    private void showThongKeTongQuat(){
        THeaderTableTKTongQuat();
        tableModel.setRowCount(0);
        List<BaiKhaoSat> list = ksdao.thongkeTongQuat();
        if(list != null){
            for (BaiKhaoSat bks : list) {
            Object[] row = new Object[]{
                bks.getId(),bks.getTieuDe(),bks.getThoiGianBatDau(),bks.getThoiGianKetThuc(),bks.getSoLuongCH(),bks.getSoLuongQN(),bks.getSoLuongPH()
            };
            tableModel.addRow(row);
            }
        }
    }
    
    private void showTimKiemTongQuat(List<BaiKhaoSat> list){
        THeaderTableTKTongQuat();
        tableModel.setRowCount(0);
        if(list != null){
            for (BaiKhaoSat bks : list) {
                Object[] row = new Object[]{
                bks.getId(),bks.getTieuDe(), bks.getThoiGianBatDau(),bks.getThoiGianKetThuc(),bks.getSoLuongCH(),bks.getSoLuongQN(),bks.getSoLuongPH()
            };
                tableModel.addRow(row);
            }
        }
    }
    
    private void showPhanHoi(){
        THeaderTableTKPhanHoi();
        tableModelPhanHoi.setRowCount(0);
        List<PhanHoi> list = ksdao.ThongKePhanHoi(idBKS);
        if(list != null){
            for (PhanHoi phanHoi : list) {
                Object[] row = new Object[]{
                    phanHoi.getTieude(), phanHoi.getHoten(), phanHoi.getCmnd(), phanHoi.getNoiDung(), phanHoi.getThoiGian()
                };
                tableModelPhanHoi.addRow(row);
            }
        }
    }
    
    private void showTimKiemPhanHoi(List<PhanHoi> list){
        THeaderTableTKPhanHoi();
        tableModel.setRowCount(0);
        if(list != null){
            for (PhanHoi phanHoi : list) {
                Object[] row = new Object[]{
                    phanHoi.getTieude(), phanHoi.getHoten(), phanHoi.getCmnd(), phanHoi.getNoiDung(), phanHoi.getThoiGian()
                };
                tableModelPhanHoi.addRow(row);
            }
        }
    }
    
    private void showNguoiThamGia(){
        THeaderTableTKNguoiThamGia();
        tableModelNguoiThamGia.setRowCount(0);
        List<QuanNhan> list = ksdao.ThongKeNguoiThamGia(idBKS);
        if(list != null){
            for (QuanNhan quanNhan : list) {
            Object[] row = new Object[]{
                quanNhan.getId(), quanNhan.getTenTaiKhoan(), quanNhan.getCmnd(), quanNhan.getHoTen(), quanNhan.getNgaySinh(), quanNhan.getCapBac().getTenCapBac(), quanNhan.getDonVi().getTenDonVi()
            };
                tableModelNguoiThamGia.addRow(row);
//                tableNguoiThamGia.setModel(tableModelNguoiThamGia);
//                tableNguoiThamGia.repaint();
//                tableNguoiThamGia.revalidate();
//                System.out.println(quanNhan.getTenTaiKhoan() + " , " +quanNhan.getHoTen());
            }
//            tableNguoiThamGia.setModel(tableModelNguoiThamGia);
//            tableNguoiThamGia.repaint();
//            tableNguoiThamGia.revalidate();
        }
    }
    
    private void showTimKiemNguoiThamGia(List<QuanNhan> list){
        THeaderTableTKNguoiThamGia();
        tableModel.setRowCount(0);
        if(list != null){
            for (QuanNhan quanNhan : list) {
                Object[] row = new Object[]{
                    quanNhan.getId(), quanNhan.getTenTaiKhoan(), quanNhan.getCmnd(), quanNhan.getHoTen(), quanNhan.getNgaySinh(), quanNhan.getCapBac().getTenCapBac(), quanNhan.getDonVi().getTenDonVi()
                };
                tableModelNguoiThamGia.addRow(row);
            }
        }
    }
    
    private void showChiTietTraLoi(){
        THeaderTableTKTraLoi();
        tableModelChiTietTraLoi.setRowCount(0);
        List<CauHoi> list = ksdao.ThongKeChiTietTraLoi(idBKS,idQN);
        System.out.println("size "+list.size());
        if(list != null){
            for (CauHoi cauHoi : list) {
            Object[] row = new Object[]{
                cauHoi.getNoiDung(), cauHoi.getLuaChon1(), cauHoi.getLuaChon2(), cauHoi.getLuaChon3(), cauHoi.getLuaChon4(), cauHoi.getHinhThuc(), cauHoi.getTraloi()
            };
                tableModelChiTietTraLoi.addRow(row);
            }
        }
    }
    
    private void showSoLuongTraLoi(){
        THeaderTableTKSoLuongTraLoi();
        tableModelTkSoLuongTraLoi.setRowCount(0);
        List<CauHoi> listSLTraLoi = ksdao.ThongKeSoLuongTraLoi(idBKS);
        List<CauHoi> list = ksdao.selectCauHoiOfBKS(idBKS);
        if(list != null){
            for (int i = 0 ; i < list.size() ; i++) {
            Object[] row1 = new Object[]{
                list.get(i).getId(),list.get(i).getNoiDung(), list.get(i).getLuaChon1(), list.get(i).getLuaChon2(), list.get(i).getLuaChon3(), list.get(i).getLuaChon4()
            };    
            Object[] row2 = new Object[]{
               listSLTraLoi.get(i).getId(),"", listSLTraLoi.get(i).getSoLuongLC1(), listSLTraLoi.get(i).getSoLuongLC2(), listSLTraLoi.get(i).getSoLuongLC3(), listSLTraLoi.get(i).getSoLuongLC4()
            };
                tableModelTkSoLuongTraLoi.addRow(row1);
                tableModelTkSoLuongTraLoi.addRow(row2);
            }
            table_TKLuaChonDapAn.getColumnModel().getColumn(1).setCellRenderer(new CenteredTableCellRenderer());
            table_TKLuaChonDapAn.getColumnModel().getColumn(2).setCellRenderer(new CenteredTableCellRenderer());
            table_TKLuaChonDapAn.getColumnModel().getColumn(3).setCellRenderer(new CenteredTableCellRenderer());
            table_TKLuaChonDapAn.getColumnModel().getColumn(4).setCellRenderer(new CenteredTableCellRenderer());
        }
    }

    private void showCapBac(List<CapBac> list){
        for(int i = 0 ; i < list.size() ; i++){
            cbTKCapBac.addItem(list.get(i).getTenCapBac());
        }
    }
    
    private void showDonVi(List<DonVi> list){
        for(int i = 0 ; i < list.size() ; i++){
            cbTKDonVi.addItem(list.get(i).getTenDonVi());
        }
    }
    
    private void setDataChart01(JPanel jpnItem){
        Map<String,Integer> map = ksdao.soLuongQuanNhanOfBKS();
        if(map != null){
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            
            for (Map.Entry<String, Integer> item : map.entrySet()) {
                dataset.addValue(item.getValue(), "Quân nhân", item.getKey());
            }
            
            JFreeChart chart = ChartFactory.createBarChart("THỐNG KÊ SỐ LƯỢNG QUÂN NHÂN THAM GIA BÀI KHẢO SÁT",
                       "Bài khảo sát", "Số lượng", dataset);
            ChartPanel chartPanel = new ChartPanel(chart);
            chartPanel.setPreferredSize(new Dimension(jpnItem.getWidth(), 250));
            
            jpnItem.removeAll();
            jpnItem.setLayout(new CardLayout());
            jpnItem.add(chartPanel);
            jpnItem.validate();
            jpnItem.repaint();
        }
    }
    
    private void setDataChart02(JPanel jpnItem){
        Map<String,Integer> map = ksdao.soLuongPhanHoiOfBKS();
        if(map != null){
            DefaultCategoryDataset dataset = new DefaultCategoryDataset();
            
            for (Map.Entry<String, Integer> item : map.entrySet()) {
                dataset.addValue(item.getValue(), "Phản hổi", item.getKey());
            }
            
            JFreeChart chart = ChartFactory.createBarChart("THỐNG KÊ SỐ LƯỢNG PHẢN HỒI CỦA BÀI KHẢO SÁT",
                       "Bài khảo sát", "Số lượng", dataset);
            ChartPanel chartPanel = new ChartPanel(chart);
            chartPanel.setPreferredSize(new Dimension(jpnItem.getWidth(), 250));
            
            jpnItem.removeAll();
            jpnItem.setLayout(new CardLayout());
            jpnItem.add(chartPanel);
            jpnItem.validate();
            jpnItem.repaint();
        }
    }
    
    private void setDataChart03(JPanel jpnItem){
        
        DefaultPieDataset dataset = new DefaultPieDataset();
        dataset.setValue(cauHoiTK_DuLieu.getLuaChon1(), cauHoiTK_SoLuong.getSoLuongLC1());
        dataset.setValue(cauHoiTK_DuLieu.getLuaChon2(), cauHoiTK_SoLuong.getSoLuongLC2());
        dataset.setValue(cauHoiTK_DuLieu.getLuaChon3(), cauHoiTK_SoLuong.getSoLuongLC3());
        dataset.setValue(cauHoiTK_DuLieu.getLuaChon4(), cauHoiTK_SoLuong.getSoLuongLC4());
        
        JFreeChart chart = ChartFactory.createPieChart(
                "CHI TIẾT SỐ LƯỢNG LỰA CHỌN CÂU TRẢ LỜI", dataset, true, true, true);
        
        ChartPanel chartPanel = new ChartPanel(chart);
            chartPanel.setPreferredSize(new Dimension(jpnItem.getWidth(), 350));
            
        PiePlot plot = (PiePlot) chart.getPlot();
        plot.setLabelGenerator(new StandardPieSectionLabelGenerator("{0}: {1} ({2})"));  
        
        // Thay đổi thuộc tính văn bản
        Font labelFont = new Font("Arial", Font.PLAIN, 14); // Chọn font, kiểu và kích thước của văn bản
        plot.setLabelFont(labelFont);
        plot.setLabelPaint(Color.BLACK); // Chọn màu sắc của văn bản
        
        jpnItem.removeAll();
        jpnItem.setLayout(new CardLayout());
        jpnItem.add(chartPanel);
        jpnItem.validate();
        jpnItem.repaint();
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BieuDoTKTraLoi;
    private javax.swing.JPanel JThongKeTongQuat;
    private javax.swing.JPanel ThongKeMain;
    private javax.swing.JButton btnBackNguoiThamGia;
    private javax.swing.JButton btnBackTQ;
    private javax.swing.JButton btnBackTongQuat;
    private javax.swing.JButton btnChiTietPhanHoi;
    private javax.swing.JButton btnChiTietThamGia;
    private javax.swing.JButton btnChiTietTraLoi;
    private javax.swing.ButtonGroup btnGroupFilterPhanHoi;
    private javax.swing.ButtonGroup btnGroupFilterSort;
    private javax.swing.ButtonGroup btnGroupNguoiThamGia;
    private javax.swing.JButton btnHuyTKNguoiThamGia;
    private javax.swing.JButton btnHuyTKPhanHoi;
    private javax.swing.JButton btnHuyTimKiem;
    private javax.swing.JButton btnQLTKTQ;
    private javax.swing.JButton btnTKNguoiThamGia;
    private javax.swing.JButton btnTKPhanHoi;
    private javax.swing.JButton btnTKSoLuongTraLoi;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXuatFile;
    private javax.swing.JButton btn_QuayLaiNguoiThamGia;
    private javax.swing.JComboBox<String> cbTKCapBac;
    private javax.swing.JComboBox<String> cbTKDonVi;
    private javax.swing.JPanel jBieuDoThongKe;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jChiTietNguoiThamGia;
    private javax.swing.JPanel jChiTietPhanHoi;
    private javax.swing.JPanel jChiTietTraLoi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JPanel jThongKeLuaChonDapAn;
    private javax.swing.JPanel jViewBieuDoTraLoi;
    private javax.swing.JPanel jpnView1;
    private javax.swing.JPanel jpnView2;
    private javax.swing.JRadioButton rdSXThoiGianPhanHoi;
    private javax.swing.JRadioButton rdSortAscByNguoiThamGia;
    private javax.swing.JRadioButton rdSortDescByPhanHoi;
    private javax.swing.JRadioButton rdTKCapBac;
    private javax.swing.JRadioButton rdTKCmndPhanHoi;
    private javax.swing.JRadioButton rdTKDonVi;
    private javax.swing.JRadioButton rdTKTenBKS;
    private javax.swing.JRadioButton rdTKTenQN;
    private javax.swing.JRadioButton rdTKTenQNPhanHoi;
    private javax.swing.JRadioButton rdTKTenTK;
    private javax.swing.JTable tableChiTietTraLoi;
    private javax.swing.JTable tableNguoiThamGia;
    private javax.swing.JTable tablePhanHoi;
    private javax.swing.JTable tableThongKe;
    private javax.swing.JTable table_TKLuaChonDapAn;
    private javax.swing.JTextField txtFilterNameBKS;
    private javax.swing.JTextField txtTKNguoiThamGia;
    private javax.swing.JTextField txtTKPhanHoi;
    // End of variables declaration//GEN-END:variables
}
