/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Admin;

import DAO.KhaoSatDAO;
import DAO.QuanNhanDAO;
import Model.CapBac;
import Model.DonVi;
import Model.QuanNhan;
import Service.Validation;
import com.sun.jdi.connect.spi.Connection;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import static java.awt.image.ImageObserver.WIDTH;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.TimerTask;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author DELL
 */
public final class QuanLyQuanNhan extends javax.swing.JPanel {
    QuanNhanDAO qndao = new QuanNhanDAO();
    KhaoSatDAO ksdao = new KhaoSatDAO();
    DefaultTableModel tableModel = new DefaultTableModel();
    
    Timer timer;
    int idQN = -1;
    
    /**
     * Creates new form ManagerUser
     */
    public QuanLyQuanNhan() {
        initComponents();
        tableModel = (DefaultTableModel) tableQuanNhan.getModel();
        showQuanNhan(list);
        showCapBac(ksdao.selectCapBac());
        showDonVi(qndao.selectDonVi());
        jTTKhoaTK.setVisible(false);
        jButtonKhoaTK.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupFilter = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableQuanNhan = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonCRUD = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnKhoaTaiKhoan = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jButtonKhoaTK = new javax.swing.JPanel();
        btnH = new javax.swing.JButton();
        btnK = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jTTDangKy = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateNgaySinh = new com.toedter.calendar.JDateChooser();
        cbCapBac = new javax.swing.JComboBox<>();
        cbDonVi = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtTenTK = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtMatkhau = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtCmnd = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTTKhoaTK = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jThoigiankhoa = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLydokhoa = new javax.swing.JTextArea();
        jTenTK = new javax.swing.JLabel();
        jEmail = new javax.swing.JLabel();
        jCmnd = new javax.swing.JLabel();
        jTenqn = new javax.swing.JLabel();
        jNgaykhoa = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtNameFilter = new javax.swing.JTextField();
        cbTrangThai = new javax.swing.JComboBox<>();
        btnTimKiem = new javax.swing.JButton();
        rdFilterName = new javax.swing.JRadioButton();
        rdFilterStatus = new javax.swing.JRadioButton();
        btnHuyTimKiem = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setBackground(new java.awt.Color(0, 153, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 0));
        jLabel1.setText("QUẢN LÝ TÀI KHOẢN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(462, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(403, 403, 403))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 50));

        tableQuanNhan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên tài khoản", "Mật khẩu", "Email", "CMND", "Họ và Tên", "Ngày Sinh", "Cấp bậc", "Đơn vị", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableQuanNhan.setRowHeight(30);
        tableQuanNhan.setShowHorizontalLines(true);
        tableQuanNhan.setShowVerticalLines(true);
        tableQuanNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableQuanNhanMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableQuanNhan);
        if (tableQuanNhan.getColumnModel().getColumnCount() > 0) {
            tableQuanNhan.getColumnModel().getColumn(0).setMaxWidth(50);
            tableQuanNhan.getColumnModel().getColumn(1).setMinWidth(150);
            tableQuanNhan.getColumnModel().getColumn(2).setMaxWidth(100);
            tableQuanNhan.getColumnModel().getColumn(3).setMinWidth(120);
            tableQuanNhan.getColumnModel().getColumn(4).setMinWidth(120);
            tableQuanNhan.getColumnModel().getColumn(5).setMinWidth(150);
            tableQuanNhan.getColumnModel().getColumn(6).setMinWidth(30);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 1120, 360));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCRUD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnThem.setBackground(new java.awt.Color(0, 153, 0));
        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnThem.setForeground(new java.awt.Color(255, 255, 0));
        btnThem.setText("Thêm Mới");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });
        jButtonCRUD.add(btnThem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 140, 40));

        btnCapNhat.setBackground(new java.awt.Color(0, 51, 255));
        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCapNhat.setForeground(new java.awt.Color(255, 255, 0));
        btnCapNhat.setText("Cập Nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });
        jButtonCRUD.add(btnCapNhat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 140, 40));

        btnXoa.setBackground(new java.awt.Color(255, 0, 0));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnXoa.setForeground(new java.awt.Color(255, 255, 0));
        btnXoa.setText("Xóa ");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });
        jButtonCRUD.add(btnXoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 140, 40));

        btnKhoaTaiKhoan.setBackground(new java.awt.Color(204, 0, 204));
        btnKhoaTaiKhoan.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKhoaTaiKhoan.setForeground(new java.awt.Color(255, 255, 0));
        btnKhoaTaiKhoan.setText("Khóa Tài Khoản");
        btnKhoaTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhoaTaiKhoanActionPerformed(evt);
            }
        });
        jButtonCRUD.add(btnKhoaTaiKhoan, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 140, 40));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (1).jpg"))); // NOI18N
        jButtonCRUD.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 150, 210));

        jPanel2.add(jButtonCRUD, new org.netbeans.lib.awtextra.AbsoluteConstraints(718, -4, 150, 210));

        jButtonKhoaTK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnH.setBackground(new java.awt.Color(255, 255, 0));
        btnH.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnH.setForeground(new java.awt.Color(0, 102, 102));
        btnH.setText("Hủy");
        btnH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHActionPerformed(evt);
            }
        });
        jButtonKhoaTK.add(btnH, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 143, 144, 43));

        btnK.setBackground(new java.awt.Color(255, 51, 0));
        btnK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnK.setForeground(new java.awt.Color(102, 0, 102));
        btnK.setText("Khóa");
        btnK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKActionPerformed(evt);
            }
        });
        jButtonKhoaTK.add(btnK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 85, 144, 46));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (2).jpg"))); // NOI18N
        jButtonKhoaTK.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 160, 200));

        jPanel2.add(jButtonKhoaTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 0, 150, 200));

        jTTDangKy.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tên Quân Nhân");
        jTTDangKy.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 6, -1, 29));

        txtHoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTTDangKy.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 6, 187, 29));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ngày Sinh");
        jTTDangKy.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 53, 107, 28));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cấp Bậc");
        jTTDangKy.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 100, 107, 29));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Đơn Vị");
        jTTDangKy.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(397, 150, 107, -1));

        dateNgaySinh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTTDangKy.add(dateNgaySinh, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 53, 187, 28));

        jTTDangKy.add(cbCapBac, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 100, 187, 29));

        jTTDangKy.add(cbDonVi, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 147, 187, 29));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tên Tài Khoản:");
        jTTDangKy.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 129, 29));

        txtTenTK.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTTDangKy.add(txtTenTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 6, 210, 29));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Mật Khẩu:");
        jTTDangKy.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 53, 129, 28));

        txtMatkhau.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTTDangKy.add(txtMatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 53, 210, 28));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email:");
        jTTDangKy.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 99, 129, 29));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTTDangKy.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 99, 210, 29));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("CMND:");
        jTTDangKy.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 146, 129, 30));

        txtCmnd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTTDangKy.add(txtCmnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 146, 210, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (1).jpg"))); // NOI18N
        jTTDangKy.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 200));

        jPanel2.add(jTTDangKy, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, -1));

        jTTKhoaTK.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Tên Tài Khoản:");
        jTTKhoaTK.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(7, 15, 117, 29));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Tên Quân Nhân");
        jTTKhoaTK.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 158, 117, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("CMND:");
        jTTKhoaTK.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 105, 117, 30));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Email:");
        jTTKhoaTK.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 56, 117, 31));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Ngày Khóa:");
        jTTKhoaTK.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 16, 95, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Khóa trong vòng:");
        jTTKhoaTK.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 153, -1, 30));

        jThoigiankhoa.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 phút (Demo)", "5 ngày", "5 tháng" }));
        jTTKhoaTK.add(jThoigiankhoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 153, 204, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Lý do khóa:");
        jTTKhoaTK.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(361, 56, 95, 31));

        jLydokhoa.setColumns(20);
        jLydokhoa.setRows(5);
        jScrollPane2.setViewportView(jLydokhoa);

        jTTKhoaTK.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 55, 216, 80));

        jTenTK.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTenTK.setForeground(new java.awt.Color(255, 255, 255));
        jTTKhoaTK.add(jTenTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 16, 202, 30));

        jEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jEmail.setForeground(new java.awt.Color(255, 255, 255));
        jTTKhoaTK.add(jEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 56, 202, 31));

        jCmnd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jCmnd.setForeground(new java.awt.Color(255, 255, 255));
        jTTKhoaTK.add(jCmnd, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 105, 202, 30));

        jTenqn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTenqn.setForeground(new java.awt.Color(255, 255, 255));
        jTTKhoaTK.add(jTenqn, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, 153, 202, 30));

        jNgaykhoa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jNgaykhoa.setForeground(new java.awt.Color(255, 255, 255));
        jTTKhoaTK.add(jNgaykhoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 16, 216, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (1).jpg"))); // NOI18N
        jTTKhoaTK.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 200));

        jPanel2.add(jTTKhoaTK, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 200));

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNameFilter.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel5.add(txtNameFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 34, 230, 32));

        cbTrangThai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbTrangThai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trạng Thái", "Hoạt động", "Bị khóa" }));
        jPanel5.add(cbTrangThai, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 103, 230, 35));

        btnTimKiem.setBackground(new java.awt.Color(0, 153, 204));
        btnTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTimKiem.setForeground(new java.awt.Color(255, 255, 0));
        btnTimKiem.setText("Tìm Kiếm");
        btnTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimKiemActionPerformed(evt);
            }
        });
        jPanel5.add(btnTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 150, 108, 40));

        btnGroupFilter.add(rdFilterName);
        rdFilterName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdFilterName.setForeground(new java.awt.Color(255, 255, 255));
        rdFilterName.setText("Tìm Kiếm theo Họ và Tên");
        jPanel5.add(rdFilterName, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 21));

        btnGroupFilter.add(rdFilterStatus);
        rdFilterStatus.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdFilterStatus.setForeground(new java.awt.Color(255, 255, 255));
        rdFilterStatus.setText("Tìm kiếm theo Trạng Thái");
        jPanel5.add(rdFilterStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 72, 230, -1));

        btnHuyTimKiem.setBackground(new java.awt.Color(255, 51, 0));
        btnHuyTimKiem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnHuyTimKiem.setForeground(new java.awt.Color(255, 255, 0));
        btnHuyTimKiem.setText("Hủy Tìm Kiếm");
        btnHuyTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyTimKiemActionPerformed(evt);
            }
        });
        jPanel5.add(btnHuyTimKiem, new org.netbeans.lib.awtextra.AbsoluteConstraints(126, 150, 110, 40));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (1).jpg"))); // NOI18N
        jPanel5.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 200));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(874, 0, 240, 200));

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 1120, 200));
    }// </editor-fold>//GEN-END:initComponents

    private void tableQuanNhanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableQuanNhanMouseClicked
        idQN = Integer.parseInt(tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 0).toString());
        String tenTk = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 1).toString();
        String matkhau = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 2).toString();
        String email = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 3).toString();
        String cmnd = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 4).toString();
        String hoten = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 5).toString();
        String ngaysinh = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 6).toString();
        String capbac = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 7).toString();
        String donvi = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 8).toString();
        
        txtTenTK.setText(tenTk);
        txtMatkhau.setText(matkhau);
        txtEmail.setText(email);
        txtCmnd.setText(cmnd);
        txtHoTen.setText(hoten);
        
        jTenTK.setText(tenTk);
        jEmail.setText(email);
        jCmnd.setText(cmnd);
        jTenqn.setText(hoten);
        
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss");
        jNgaykhoa.setText(java.time.LocalDateTime.now().format(formatter)+"");
        
        try {
            Date dateBth = new SimpleDateFormat("yyyy-MM-dd").parse(ngaysinh);
            dateNgaySinh.setDate(dateBth);
        } catch (ParseException ex) {
            System.out.println(ex.getMessage());
        }
        switch(capbac){
            case "Thiếu Úy" -> cbCapBac.setSelectedIndex(0);
            case "Trung Úy" -> cbCapBac.setSelectedIndex(1);
            case "Thượng Úy" -> cbCapBac.setSelectedIndex(2);
        }
        
        switch(donvi){
            case "Trung Đội I" -> cbDonVi.setSelectedIndex(0);
            case "Trung Đội II" -> cbDonVi.setSelectedIndex(1);
            case "Đại Đội III" -> cbDonVi.setSelectedIndex(2);
            case "Đại Đội IV" -> cbDonVi.setSelectedIndex(3);
        }
        
        
//        String image = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 8).toString();
//        if(!image.equals("null")){
//            ImageIcon imageIcon = new ImageIcon(image);
//            // Resize Image
//            Image imageResize = imageIcon.getImage().getScaledInstance(displayImage.getWidth(), displayImage.getHeight(), Image.SCALE_SMOOTH);
//            displayImage.setIcon(new ImageIcon(imageResize));
//        }
    }//GEN-LAST:event_tableQuanNhanMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        if(Validation.isEmpty(txtTenTK.getText()) || Validation.isEmpty(txtMatkhau.getText()) || Validation.isEmpty(txtEmail.getText()) || Validation.isEmpty(txtCmnd.getText())
                || Validation.isEmpty(txtHoTen.getText()) || dateNgaySinh.getDate() == null){
            showError("Vui lòng điền đầy đủ thông tin");
        }
        else if(tableQuanNhan.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn tài khoản cần xóa","Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
        else{
            String id = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 0).toString();
            boolean delete = qndao.deleteQuanNhan(Integer.parseInt(id));
            if(!delete){
                JOptionPane.showMessageDialog(null, "Xóa Quân Nhân thành công");
                tableModel.removeRow(tableQuanNhan.getSelectedRow());
                reset();
            }else{
                JOptionPane.showMessageDialog(null, "Xóa Quân Nhân thất bại");
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        String tenTk    = txtTenTK.getText();
        String matkhau  = txtMatkhau.getText();
        String email    = txtEmail.getText();
        String cmnd     = txtCmnd.getText();
        String hoten    = txtHoTen.getText();
        
        if(Validation.isEmpty(tenTk) || Validation.isEmpty(matkhau) || Validation.isEmpty(email) || Validation.isEmpty(cmnd)
                || Validation.isEmpty(hoten) || dateNgaySinh.getDate() == null){
            showError("Vui lòng điền đầy đủ thông tin");
        }else if(!ngayHopLe(dateNgaySinh.getDate())){
            showError("Ngày sinh không hợp lệ");
        }else if(qndao.kiemTraEmailTonTai(email, idQN)){
            showError("Email này đã tồn tại !");
        }
        else{
            String id = tableQuanNhan.getValueAt(tableQuanNhan.getSelectedRow(), 0).toString();
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String ngaySinh = dateFormat.format(dateNgaySinh.getDate());

            CapBac capBac = new CapBac(cbCapBac.getSelectedIndex() + 1, cbCapBac.getItemAt(cbCapBac.getSelectedIndex()));
            DonVi donVi   = new DonVi(cbDonVi.getSelectedIndex() + 1, cbDonVi.getItemAt(cbDonVi.getSelectedIndex()));
            
            QuanNhan quanNhan = new QuanNhan(Integer.parseInt(id),tenTk, matkhau, email, cmnd,hoten, 
                                        LocalDate.parse(ngaySinh), capBac, donVi,1,null);
            boolean update = qndao.updateQuanNhan(quanNhan);
            if(!update){
                JOptionPane.showMessageDialog(null, "Cập nhật Quân Nhân thành công");
                tableQuanNhan.setValueAt(tenTk, tableQuanNhan.getSelectedRow(), 1);
                tableQuanNhan.setValueAt(matkhau, tableQuanNhan.getSelectedRow(), 2);
                tableQuanNhan.setValueAt(email, tableQuanNhan.getSelectedRow(), 3);
                tableQuanNhan.setValueAt(cmnd, tableQuanNhan.getSelectedRow(), 4);
                tableQuanNhan.setValueAt(hoten, tableQuanNhan.getSelectedRow(), 5);
                tableQuanNhan.setValueAt(ngaySinh, tableQuanNhan.getSelectedRow(), 6);
                tableQuanNhan.setValueAt(cbCapBac.getItemAt(cbCapBac.getSelectedIndex()), tableQuanNhan.getSelectedRow(), 7);
                tableQuanNhan.setValueAt(cbDonVi.getItemAt(cbDonVi.getSelectedIndex()), tableQuanNhan.getSelectedRow(), 8);
                reset();
            }else{
                JOptionPane.showMessageDialog(null, "Cập nhật Quân Nhân thất bại");
            }
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimKiemActionPerformed
        if(rdFilterName.isSelected()){
            cbTrangThai.setSelectedIndex(0);
            String key = txtNameFilter.getText();
            if (key.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Vui lòng nhập tên Quân Nhân cần tìm kiếm!");
            } else {
                List<QuanNhan> listResult = searchQuanNhanByName(list, key);
                tableModel.setRowCount(0);
                showQuanNhan(listResult);
            }
        }else if(rdFilterStatus.isSelected()){
            List<QuanNhan> listResult = new ArrayList<>();
            String key = cbTrangThai.getItemAt(cbTrangThai.getSelectedIndex());
            
            if(key.equals("Trạng Thái")){
                JOptionPane.showMessageDialog(null, "Vui lòng lựa chọn trạng thái tìm kiếm");
            }else{
                for (QuanNhan quanNhan : list) {
                    if(key.equalsIgnoreCase(quanNhan.getTrangThai())){
                        listResult.add(quanNhan);
                    }
                }
                tableModel.setRowCount(0);
                showQuanNhan(listResult);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Vui lòng lựa chọn hình thức tìm kiếm !");
        }
    }//GEN-LAST:event_btnTimKiemActionPerformed

    private void btnHuyTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyTimKiemActionPerformed
        List<QuanNhan> list = qndao.selectQuanNhan();
        txtNameFilter.setText("");
        cbTrangThai.setSelectedIndex(0);
        btnGroupFilter.clearSelection();
        tableModel.setRowCount(0);
        showQuanNhan(list);
    }//GEN-LAST:event_btnHuyTimKiemActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        String tenTk    = txtTenTK.getText();
        String matkhau  = txtMatkhau.getText();
        String email    = txtEmail.getText();
        String cmnd     = txtCmnd.getText();
        String hoten    = txtHoTen.getText();
        
        if(Validation.isEmpty(tenTk) || Validation.isEmpty(matkhau) || Validation.isEmpty(email) || Validation.isEmpty(cmnd)
                || Validation.isEmpty(hoten) || dateNgaySinh.getDate() == null){
            showError("Vui lòng điền đầy đủ thông tin");
        }else if(!ngayHopLe(dateNgaySinh.getDate())){
            showError("Ngày sinh không hợp lệ");
        }else if(qndao.kiemTraEmailTonTai(email,-1)){
            showError("Email này đã tồn tại !");
        }else if(cmnd.trim().length() > 12 || cmnd.trim().length() < 12){
            showError("Chứng minh nhân nhân phải đủ 12 số");
        }
        else{
            SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
            String ngaySinh = dateFormat.format(dateNgaySinh.getDate());
            
            CapBac capBac = new CapBac(cbCapBac.getSelectedIndex() + 1, cbCapBac.getItemAt(cbCapBac.getSelectedIndex()));
            DonVi donVi   = new DonVi(cbDonVi.getSelectedIndex() + 1, cbDonVi.getItemAt(cbDonVi.getSelectedIndex()));
            
            QuanNhan quanNhan = new QuanNhan(tenTk, matkhau, email, cmnd,hoten, LocalDate.parse(ngaySinh), capBac, donVi,1,"Hoạt động");
            
            if(!qndao.them(quanNhan)){
                JOptionPane.showMessageDialog(null, "Thêm Quân Nhân thành công");
                tableModel.setRowCount(0);
                List<QuanNhan> list = qndao.selectQuanNhan();
                showQuanNhan(list);
                reset();
            }else{
                JOptionPane.showMessageDialog(null, "Thêm Quân Nhân thất bại");
            }
        }
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnKhoaTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhoaTaiKhoanActionPerformed
        if(tableQuanNhan.getSelectedRowCount() == 0){
            JOptionPane.showMessageDialog(null, "Vui lòng chọn tài khoản cần khóa","Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
        else{
            jTTDangKy.setVisible(false);
            jTTKhoaTK.setVisible(true);
            jButtonCRUD.setVisible(false);
            jButtonKhoaTK.setVisible(true);
        }
        
    }//GEN-LAST:event_btnKhoaTaiKhoanActionPerformed

    private void btnHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHActionPerformed
       jTTDangKy.setVisible(true);
       jTTKhoaTK.setVisible(false);
       jButtonKhoaTK.setVisible(false);
       jButtonCRUD.setVisible(true);
    }//GEN-LAST:event_btnHActionPerformed

    private void btnKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKActionPerformed
        String lydo = jLydokhoa.getText();
        String tg   = jThoigiankhoa.getItemAt(jThoigiankhoa.getSelectedIndex());
        
        if(Validation.isEmpty(lydo)){
            showError("Vui lòng điền lý do khóa tài khoản !");
        }
        else{
            // update trạng thái tài khoản thành "Đang khóa"
            // Bắt đầu chạy Timer theo thời gian cần khóa
            int tgKhoa = Integer.parseInt(tg.trim().split(" ")[0]);
            String mocThoiGian = tg.trim().split(" ")[1];
            if(!qndao.khoaTaiKhoan(idQN, "Bị khóa", lydo)){
                JOptionPane.showMessageDialog(null, "Khóa tài khoản thành công !");
                reset();
                tableModel.setRowCount(0);
                List<QuanNhan> list = qndao.selectQuanNhan();
                showQuanNhan(list);
                jTTDangKy.setVisible(true);
                jTTKhoaTK.setVisible(false);
                jButtonCRUD.setVisible(true);
                jButtonKhoaTK.setVisible(false);
                
            }else{
                JOptionPane.showMessageDialog(null, "Khóa tài khoản thất bại !");
            }
            
            long[] thoiGianChay = { 0 };
            long[] numberOfMilliseconds = { 0 };
            
            if(mocThoiGian.equalsIgnoreCase("phút")){
                numberOfMilliseconds[0] = tgKhoa * 60 * 1000;
            }else if(mocThoiGian.equalsIgnoreCase("ngày")){
                numberOfMilliseconds[0] = tgKhoa * 24 * 60 * 60 * 1000;
            }else if(mocThoiGian.equalsIgnoreCase("tháng")){
                numberOfMilliseconds[0] = tgKhoa * 30 * 24 * 60 * 60 * 1000;
            }
            
            Timer timer = new Timer(1000, new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    thoiGianChay[0] += 1000;
                    if (thoiGianChay[0] >= numberOfMilliseconds[0]) {
                        // Đã chạy đủ 5 ngày, dừng Timer
                        ((Timer) e.getSource()).stop();

                        // Cập nhật trạng thái tài khoản
                        if(!qndao.khoaTaiKhoan(idQN, "Hoạt động", null)){
//                            JOptionPane.showMessageDialog(null, "Mở tài khoản thành công !");
                            
                            tableModel.setRowCount(0);
                            List<QuanNhan> list = qndao.selectQuanNhan();
                            showQuanNhan(list);
                        }
                    }
                }
            });

            // Bắt đầu timer
            timer.start();
        }
    }//GEN-LAST:event_btnKActionPerformed
    
    private boolean ngayHopLe(Date date){
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String ngay = dateFormat.format(date);
        
        LocalDate dateSS = LocalDate.parse(ngay);
        
        LocalDate dateCur = LocalDate.now();
        if(dateSS.isAfter(dateCur)){
            return false;
        }
        return true;
    }
    
    private List<QuanNhan> searchQuanNhanByName(List<QuanNhan> list, String key){
        List<QuanNhan> resultList = new ArrayList<>();
        var regex = ".*" + key + ".*";
        Pattern pattern = Pattern.compile(regex, Pattern.CASE_INSENSITIVE);
        Matcher matcher;
        for (QuanNhan quanNhan : list) {
            matcher = pattern.matcher(quanNhan.getHoTen());
            if (matcher.matches()) {
                resultList.add(quanNhan);
            }
        }
        return resultList;
    }
    
    private void showError(String str){
        JOptionPane.showMessageDialog(null, str,"Lỗi", JOptionPane.ERROR_MESSAGE);
    }
    
    private void showCapBac(List<CapBac> list){
        for(int i = 0 ; i < list.size() ; i++){
            cbCapBac.addItem(list.get(i).getTenCapBac());
        }
    }
    private void showDonVi(List<DonVi> list){
        for(int i = 0 ; i < list.size() ; i++){
            cbDonVi.addItem(list.get(i).getTenDonVi());
        }
    }
    
    private void THeaderTable(){
        JTableHeader header = tableQuanNhan.getTableHeader();
        header.setFont(new Font("SansSerif", WIDTH, 14));
    }
    
    List<QuanNhan> list = qndao.selectQuanNhan();
    private void showQuanNhan(List<QuanNhan> list){
        THeaderTable();
        for (QuanNhan qn : list) {
            Object[] row = new Object[]{
                qn.getId(),qn.getTenTaiKhoan(),qn.getMatKhau(),qn.getEmail(),qn.getCmnd(),qn.getHoTen(),qn.getNgaySinh(),
                qn.getCapBac().getTenCapBac(), qn.getDonVi().getTenDonVi(), qn.getTrangThai()
            };
            tableModel.addRow(row);
        }
    }
    
    public void reset(){
        jLydokhoa.setText("");
        txtTenTK.setText("");
        txtMatkhau.setText("");
        txtEmail.setText("");
        txtCmnd.setText("");
        txtHoTen.setText("");
        dateNgaySinh.setDate(null);
        cbCapBac.setSelectedIndex(0);
        cbDonVi.setSelectedIndex(0);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.ButtonGroup btnGroupFilter;
    private javax.swing.JButton btnH;
    private javax.swing.JButton btnHuyTimKiem;
    private javax.swing.JButton btnK;
    private javax.swing.JButton btnKhoaTaiKhoan;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JComboBox<String> cbCapBac;
    private javax.swing.JComboBox<String> cbDonVi;
    private javax.swing.JComboBox<String> cbTrangThai;
    private com.toedter.calendar.JDateChooser dateNgaySinh;
    private javax.swing.JPanel jButtonCRUD;
    private javax.swing.JPanel jButtonKhoaTK;
    private javax.swing.JLabel jCmnd;
    private javax.swing.JLabel jEmail;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextArea jLydokhoa;
    private javax.swing.JLabel jNgaykhoa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jTTDangKy;
    private javax.swing.JPanel jTTKhoaTK;
    private javax.swing.JLabel jTenTK;
    private javax.swing.JLabel jTenqn;
    private javax.swing.JComboBox<String> jThoigiankhoa;
    private javax.swing.JRadioButton rdFilterName;
    private javax.swing.JRadioButton rdFilterStatus;
    private javax.swing.JTable tableQuanNhan;
    private javax.swing.JTextField txtCmnd;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtMatkhau;
    private javax.swing.JTextField txtNameFilter;
    private javax.swing.JTextField txtTenTK;
    // End of variables declaration//GEN-END:variables
}
