/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.User;

import DAO.QuanNhanDAO;
import View.Admin.MainDisplay;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class MainDisplayUser extends javax.swing.JFrame {
    int idUser;
    String capbac = "";
    QuanNhanDAO qndao = new QuanNhanDAO();
    String confirmThoat;
    /**
     * Creates new form MainDisplay
     * @param id
     * @param capbac
     */
    public MainDisplayUser(int id,String capbac) {
        initComponents();
        setLocationRelativeTo(null);
//        if(userDAO.selectStatisticById(id)){
//            btnUserExam.setEnabled(false);
//        }
        tabMainUser.add(new InfromationUser(id));
        this.idUser = id;
        this.capbac = capbac;
    }
    
    public MainDisplayUser() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        anhnen = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnInfoUser = new javax.swing.JButton();
        btnUserExam = new javax.swing.JButton();
        btnResultExam = new javax.swing.JButton();
        btnDangXuat = new javax.swing.JButton();
        tabMainUser = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        anhnen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/anhnen.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(anhnen, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(anhnen, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 200));

        jPanel2.setLayout(new java.awt.GridLayout(4, 0, 0, 15));

        btnInfoUser.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnInfoUser.setText("Thông Tin Quân Nhân");
        btnInfoUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInfoUsertnInfoUserActionPerformed(evt);
            }
        });
        jPanel2.add(btnInfoUser);

        btnUserExam.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnUserExam.setText("Thực Hiện Khảo Sát");
        btnUserExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUserExbtnUserExammActionPerformed(evt);
            }
        });
        jPanel2.add(btnUserExam);

        btnResultExam.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnResultExam.setText("Chi Tiết Khảo Sát");
        btnResultExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultExamActionPerformed(evt);
            }
        });
        jPanel2.add(btnResultExam);

        btnDangXuat.setBackground(new java.awt.Color(255, 51, 0));
        btnDangXuat.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDangXuat.setForeground(new java.awt.Color(0, 51, 51));
        btnDangXuat.setText("Đăng Xuất");
        btnDangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangXuatActionPerformed(evt);
            }
        });
        jPanel2.add(btnDangXuat);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 250));
        getContentPane().add(tabMainUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1110, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnInfoUsertnInfoUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInfoUsertnInfoUserActionPerformed
        String namebtn = btnInfoUser.getActionCommand();
        if(namebtn.equals("Thông Tin Quân Nhân")){
            if(tabMainUser.getTabCount() != 0){
                tabMainUser.removeAll();
            }
            tabMainUser.add("Thông Tin Quân Nhân", new InfromationUser(idUser));
        }
    }//GEN-LAST:event_btnInfoUsertnInfoUserActionPerformed

    private void btnUserExbtnUserExammActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUserExbtnUserExammActionPerformed
        String namebtn = btnUserExam.getActionCommand();
        boolean check = false;
//        if(namebtn.equals("Thực Hiện Khảo Sát")){
            if(tabMainUser.getTabCount() != 0){
                tabMainUser.removeAll();
//            }
            tabMainUser.add("Thực Hiện Khảo Sát", new ThamGiaKhaoSat(idUser,capbac));
        }
    }//GEN-LAST:event_btnUserExbtnUserExammActionPerformed

    private void btnResultExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultExamActionPerformed
        String namebtn = btnResultExam.getActionCommand();
        if(namebtn.equals("Chi Tiết Khảo Sát")){
            if(tabMainUser.getTabCount() != 0){
                tabMainUser.removeAll();
            }
            tabMainUser.add("Chi Tiết Khảo Sát", new ChiTietKhaoSat(idUser));
        }
    }//GEN-LAST:event_btnResultExamActionPerformed

    private void btnDangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangXuatActionPerformed
        int choice = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn thoát ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
        if (choice == JOptionPane.YES_OPTION) {
           this.setVisible(false);
           new Login_Form().setVisible(true);
        } 
    }//GEN-LAST:event_btnDangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDisplayUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDisplayUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDisplayUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDisplayUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDisplayUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel anhnen;
    private javax.swing.JButton btnDangXuat;
    private javax.swing.JButton btnInfoUser;
    private javax.swing.JButton btnResultExam;
    private javax.swing.JButton btnUserExam;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane tabMainUser;
    // End of variables declaration//GEN-END:variables
}
