/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.User;

import DAO.KhaoSatDAO;
import DAO.QuanNhanDAO;
import Model.BaiKhaoSat;
import Model.TraLoi;
import Model.CauHoi;
import Model.PhanHoi;
import Model.QuanNhan;
import Service.Validation;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Insets;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BoxLayout;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JViewport;


/**
 *
 * @author DELL
 */
public class ThamGiaKhaoSat extends javax.swing.JPanel{

    QuanNhanDAO qndao = new QuanNhanDAO();
    KhaoSatDAO ksdao = new KhaoSatDAO();
    int idQN;
    String capbac = "";
    int numberQues = 0;
    int positionQuestion = 0;
    int positionQuestionPrevious = -1;
    int positionClickLanDau = 0;
    int idBKS = -1;
    boolean check;

    /**
     * Creates new form UserExam
     *
     * @param id
     * @param capbac
     */
    public ThamGiaKhaoSat(int id,String capbac) {
        initComponents();
        JUserExam.setVisible(false);
        KetQuaBKS.setVisible(false);
        JInfoExam.setVisible(true);
        idQN = id;
        this.capbac = capbac;
        showDanhSachBKS();
        btnPrevious.setVisible(false);
        btnSubmit.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        KetQuaBKS = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPhanHoi = new javax.swing.JTextArea();
        btnKetThucBKS = new javax.swing.JButton();
        btnQuayLaiBKS = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JUserExam = new javax.swing.JPanel();
        jshowQuestion = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtSoCau = new javax.swing.JLabel();
        jNumberQuestion = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        JInfoExam = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        btnStartExam = new javax.swing.JButton();
        showDanhSachBKS = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        KetQuaBKS.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(204, 204, 255));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cảm ơn bạn đã dành thời gian tham gia bài khảo sát của chúng tôi");
        jPanel10.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(198, 15, -1, 50));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("/*********************************** CHÚC BẠN MỘT NGÀY VUI VẺ ***********************************/");
        jPanel10.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 748, 31));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (2).jpg"))); // NOI18N
        jPanel10.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 120));

        KetQuaBKS.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, -1));

        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Bạn có ý kiến phản hồi gì về bài khảo sát này không ?");
        jPanel11.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 633, 29));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nếu không ý nào vui lòng điền \"Không có\" . Xin cảm ơn !");
        jPanel11.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 41, 633, 31));

        txtPhanHoi.setColumns(20);
        txtPhanHoi.setRows(5);
        jScrollPane1.setViewportView(txtPhanHoi);

        jPanel11.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 90, 761, 274));

        btnKetThucBKS.setBackground(new java.awt.Color(0, 204, 0));
        btnKetThucBKS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKetThucBKS.setForeground(new java.awt.Color(255, 255, 0));
        btnKetThucBKS.setText("Kết thúc khảo sát");
        btnKetThucBKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKetThucBKSActionPerformed(evt);
            }
        });
        jPanel11.add(btnKetThucBKS, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 382, 151, 50));

        btnQuayLaiBKS.setBackground(new java.awt.Color(255, 51, 0));
        btnQuayLaiBKS.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnQuayLaiBKS.setForeground(new java.awt.Color(255, 255, 255));
        btnQuayLaiBKS.setText("Quay lại bài khảo sát");
        btnQuayLaiBKS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuayLaiBKSActionPerformed(evt);
            }
        });
        jPanel11.add(btnQuayLaiBKS, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 382, -1, 50));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (2).jpg"))); // NOI18N
        jPanel11.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 480));

        KetQuaBKS.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(205, 120, 770, 473));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (2).jpg"))); // NOI18N
        KetQuaBKS.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 600));

        add(KetQuaBKS, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        JUserExam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jshowQuestion.setBackground(new java.awt.Color(255, 255, 255));
        jshowQuestion.setLayout(new java.awt.CardLayout());
        JUserExam.add(jshowQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 710, 450));

        jPanel2.setBackground(new java.awt.Color(0, 0, 51));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Số Câu Hỏi:");

        txtSoCau.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtSoCau.setForeground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(txtSoCau, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                    .addComponent(txtSoCau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        JUserExam.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 0, 390, 70));

        jNumberQuestion.setBackground(new java.awt.Color(0, 0, 51));
        jNumberQuestion.setLayout(new java.awt.GridLayout(5, 4, 10, 10));
        JUserExam.add(jNumberQuestion, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 390, 450));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Đã trả lời");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Chưa trả lời");

        jLabel9.setBackground(new java.awt.Color(0, 204, 0));
        jLabel9.setForeground(new java.awt.Color(0, 153, 51));
        jLabel9.setOpaque(true);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setOpaque(true);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(206, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        JUserExam.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 390, 90));

        jPanel5.setBackground(new java.awt.Color(0, 0, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 710, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        JUserExam.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 70));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        btnNext.setBackground(new java.awt.Color(0, 153, 0));
        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnNext.setForeground(new java.awt.Color(255, 255, 0));
        btnNext.setText("Câu Tiếp Theo");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setBackground(new java.awt.Color(0, 153, 153));
        btnPrevious.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnPrevious.setForeground(new java.awt.Color(255, 255, 0));
        btnPrevious.setText("Câu Trước");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnSubmit.setBackground(new java.awt.Color(255, 102, 0));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 0));
        btnSubmit.setText("Hoàn Thành");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrevious, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 296, Short.MAX_VALUE)
                .addComponent(btnSubmit)
                .addGap(18, 18, 18)
                .addComponent(btnNext)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnPrevious, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        JUserExam.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 710, 90));

        add(JUserExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 610));

        JInfoExam.setBackground(new java.awt.Color(255, 255, 255));
        JInfoExam.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ABnaii.jpg"))); // NOI18N
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 580));

        JInfoExam.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 380, 570));

        jPanel8.setBackground(new java.awt.Color(0, 0, 51));
        jPanel8.setForeground(new java.awt.Color(255, 255, 0));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("THỰC HIỆN BÀI KHẢO SÁT");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(363, Short.MAX_VALUE)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(250, 250, 250))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        JInfoExam.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 50));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnStartExam.setBackground(new java.awt.Color(0, 153, 0));
        btnStartExam.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnStartExam.setForeground(new java.awt.Color(255, 255, 0));
        btnStartExam.setText("Thực hiện khảo sát");
        btnStartExam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartExamActionPerformed(evt);
            }
        });
        jPanel9.add(btnStartExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 470, 189, 51));

        showDanhSachBKS.setBackground(new java.awt.Color(51, 51, 51));
        showDanhSachBKS.setForeground(new java.awt.Color(51, 51, 51));
        showDanhSachBKS.setAutoscrolls(true);
        jPanel9.add(showDanhSachBKS, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 6, 652, 450));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/ABnaii.jpg"))); // NOI18N
        jPanel9.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 710, 590));

        JInfoExam.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 710, 580));

        add(JInfoExam, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 600));
    }// </editor-fold>//GEN-END:initComponents
    
    ActionListener actionListener = new ActionListener(){
        @Override
        public void actionPerformed(ActionEvent e) {
        CardLayout cardLayout = (CardLayout) jshowQuestion.getLayout();
            System.out.println("Click button ");
            cardLayout.show(jshowQuestion, e.getActionCommand());
            
            List<CauHoi> questions = ksdao.selectCauHoiOfBKS(idBKS);
            positionQuestion = Integer.parseInt(e.getActionCommand()) - 1;
            
            if(positionQuestionPrevious != positionQuestion){
                if(positionQuestionPrevious != -1){
                    Component[] components = jshowQuestion.getComponents();
                    JPanel jPanel = (JPanel) components[positionQuestionPrevious];
                    getSelected(jPanel);
                    Component[] components1 = jNumberQuestion.getComponents();
                    if (check) {
                        components1[positionQuestionPrevious].setBackground(Color.green);
                    }else {
                        components1[positionQuestionPrevious].setBackground(Color.white);
                    } 
                }else{
                    Component[] components = jshowQuestion.getComponents();
                    JPanel jPanel = (JPanel) components[positionClickLanDau];
                    getSelected(jPanel);
                    Component[] components1 = jNumberQuestion.getComponents();
                    if (check) {
                        components1[positionClickLanDau].setBackground(Color.green);
                    } 
                }
                
                positionQuestionPrevious = positionQuestion;
            }
            
            
            
            System.out.println(positionQuestion);
            btnPrevious.setVisible(true);
            if (positionQuestion == questions.size() - 1) {
                btnNext.setVisible(false);
                btnSubmit.setVisible(true);
            }else if(positionQuestion == 0){
                btnNext.setVisible(true);
                btnPrevious.setVisible(false);
                btnSubmit.setVisible(false);
            }else{
                btnSubmit.setVisible(false);
                btnNext.setVisible(true);
                btnPrevious.setVisible(true);
            }
        }
    };
    
    
    
    private void btnStartExamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartExamActionPerformed
        JRadioButton selectedRadioButton = null;
        for (JRadioButton radioButton : radioButtonList) {
            if (radioButton.isSelected()) {
                selectedRadioButton = radioButton;
                break;
            }
        }
        
        if (selectedRadioButton == null) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn bài khảo sát bạn muốn thực hiện !");
        }
        else
        {
            JInfoExam.setVisible(false);
            JUserExam.setVisible(true);
            
            idBKS = (int) selectedRadioButton.getClientProperty("BaiKhaoSatID");
            System.out.println("ID BKS "+idBKS);
            List<CauHoi> cauHois = ksdao.selectCauHoiOfBKS(idBKS);
            numberQues = cauHois.size();

            for (int i = 1; i <= numberQues; i++) {
                JButton button = new JButton(i+"");
                button.setFont(new Font("Segoe UI", 1, 16));
                button.setBackground(Color.WHITE);
                jNumberQuestion.add(button);

                button.addActionListener(actionListener);
            }


            System.out.println(cauHois.size());
            for (int i = 0; i < cauHois.size(); i++) {
                System.out.println(cauHois.get(i).getHinhThuc());
                if(cauHois.get(i).getHinhThuc().equalsIgnoreCase("Đa lựa chọn")){
                    FormDaLuaChon questionForm = new FormDaLuaChon(cauHois.get(i), i + 1);
                    jshowQuestion.add(questionForm,(i+1)+"");
                }else if(cauHois.get(i).getHinhThuc().equalsIgnoreCase("Đơn lựa chọn")){
                    FormDonLuaChon questionForm = new FormDonLuaChon(cauHois.get(i), i + 1);
                    jshowQuestion.add(questionForm,(i+1)+"");
                }else{
                    FormTuLuan questionForm = new FormTuLuan(cauHois.get(i), i + 1);
                    jshowQuestion.add(questionForm,(i+1)+"");
                }

            }
    //        startTimmer();
            txtSoCau.setText(numberQues+"");
            jshowQuestion.setVisible(true);
            JInfoExam.setVisible(false);
            KetQuaBKS.setVisible(false);
        }
    }//GEN-LAST:event_btnStartExamActionPerformed

    
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        CardLayout questionForm = (CardLayout) jshowQuestion.getLayout();

        Component[] components = jshowQuestion.getComponents();
        System.out.println(components.length);
        JPanel jPanel = (JPanel) components[positionQuestion];
        getSelected(jPanel);

        if (!check) {
            JOptionPane.showMessageDialog(null, "Vui lòng chọn câu trả lời");
        } else {
            List<CauHoi> questions = ksdao.selectCauHoiOfBKS(idBKS);
            questionForm.next(jshowQuestion);
            Component[] components1 = jNumberQuestion.getComponents();
            if (check) {
                components1[positionQuestion].setBackground(Color.green);
            } 
            btnPrevious.setVisible(true);
            positionQuestion++;
            positionClickLanDau++;
            if (positionQuestion == questions.size() - 1) {
                btnNext.setVisible(false);
                btnSubmit.setVisible(true);
            }
        }
    }//GEN-LAST:event_btnNextActionPerformed
    private void clickButton(){
        Component[] compButton = jNumberQuestion.getComponents();
        
        for (int i = 0; i < compButton.length; i++) {
            System.out.println("chạy vào click button ");
            if(compButton[i] instanceof JButton){
                JButton jButton = (JButton) compButton[i];
                jButton.addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    CardLayout cardLayout = (CardLayout) jshowQuestion.getLayout();

                    Component[] components = jshowQuestion.getComponents();
                    JPanel jPanel = (JPanel) components[Integer.parseInt(e.getActionCommand()) -1];
                    getSelected(jPanel);
                    
                    if (!check) {
                        JOptionPane.showMessageDialog(null, "Vui lòng chọn câu trả lời");
                    }else{
                        cardLayout.show(jshowQuestion, e.getActionCommand());
                    }
                }
            });
            }
        }
    }
    
    private void getSelected(JPanel panel) {
        check = false;
        Component[] components = panel.getComponents();
        for (Component component : components) {
            if (component instanceof JCheckBox box) {
                
                if (box.isSelected()) {
                    System.out.println("J Check box");
                    check = true;
                    break;
                }
            }
            else if (component instanceof JRadioButton radioButton) {
                if (radioButton.isSelected()) {
                    System.out.println("J Radio box");
                    check = true;
                    break;
                }
            }
            else if(component instanceof JScrollPane jScrollPane){
                System.out.println("JTextArea JTextArea JTextArea");
                JScrollPane scrollPane = jScrollPane;
                JViewport viewport = scrollPane.getViewport();
                Component comp = viewport.getView();
                if (comp instanceof JTextArea jTextArea) {
                    String noidung = jTextArea.getText();
                    if (!noidung.isEmpty()) {
                    check = true;
                    break;
                }
            }
        }
            
        }
    }

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        CardLayout questionForm = (CardLayout) jshowQuestion.getLayout();
        questionForm.previous(jshowQuestion);
        
        Component[] components = jshowQuestion.getComponents();
        JPanel jPanel = (JPanel) components[positionQuestion];
        getSelected(jPanel);
        Component[] components1 = jNumberQuestion.getComponents();
        if (check) {
            components1[positionQuestion].setBackground(Color.green);
        }
        
        
        btnSubmit.setVisible(false);
        btnNext.setVisible(true);
        --positionQuestion;
        --positionClickLanDau;
        if (positionQuestion == 0) {
            btnPrevious.setVisible(false);
        }
    }//GEN-LAST:event_btnPreviousActionPerformed

    
    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

            List<CauHoi> cauHois = ksdao.selectCauHoiOfBKS(idBKS);
            List<TraLoi> traLois = new ArrayList<>();
            boolean allAnswered = true; // Biến kiểm tra xem đã trả lời hết tất cả các câu hỏi hay chưa
            
            for(int i = 0; i < cauHois.size() ; i++){
                String noidung = "";
                int idCauHoi = cauHois.get(i).getId();
                
                if(cauHois.get(i).getHinhThuc().equals("Đơn lựa chọn")){
                    // Nếu câu hỏi là đơn lựa chọn, tìm ra các đáp án được chọn và lưu vào danh sách selectedAnswers
                    Component[] components = jshowQuestion.getComponents();
                    if(components[i] instanceof JPanel){
                        JPanel jPanel = (JPanel) components[i];
                        Component[] compJpanel = jPanel.getComponents();
                        
                        boolean answered = false; // Biến kiểm tra xem câu hỏi đã được trả lời hay chưa
                        
                        for (Component component : compJpanel) {
                            if (component instanceof JRadioButton) {
                                JRadioButton radioButton = (JRadioButton) component;
                                if (radioButton.isSelected()) {
                                    noidung = radioButton.getActionCommand();
                                    answered = true;
                                    break;
                                }
                            }
                        }
                        
                        if (!answered) {
                            allAnswered = false;
                        }
                    }
                }
                else if(cauHois.get(i).getHinhThuc().equals("Đa lựa chọn")){
                    // Nếu câu hỏi là đa lựa chọn, tìm ra các đáp án được chọn và lưu vào danh sách selectedAnswers
                    Component[] components = jshowQuestion.getComponents();
                    if(components[i] instanceof JPanel){
                        JPanel jPanel = (JPanel) components[i];
                        Component[] compJpanel = jPanel.getComponents();
                        
                        boolean answered = false; // Biến kiểm tra xem câu hỏi đã được trả lời hay chưa
                        
                        for (Component component : compJpanel) {
                            if (component instanceof JCheckBox) {
                                JCheckBox checkBox = (JCheckBox) component;
                                if (checkBox.isSelected()) {
                                    noidung += checkBox.getActionCommand() + " ; ";
                                    answered = true;
                                }
                            }
                        }
                        
                        if (!answered) {
                            allAnswered = false;
                        }
                        
                    }
                }else if (cauHois.get(i).getHinhThuc().equals("Tự luận")){
                    // Nếu câu hỏi là tự luận
                    System.out.println("Tự luận");
                    Component[] components = jshowQuestion.getComponents();
                    if(components[i] instanceof JPanel){
                        JPanel jPanel = (JPanel) components[i];
                        Component[] compJpanel = jPanel.getComponents();
                        
                        boolean answered = false; // Biến kiểm tra xem câu hỏi đã được trả lời hay chưa
                        
                        for (Component component : compJpanel) {
                            if (component instanceof JScrollPane) {
                                JScrollPane scrollPane = (JScrollPane) component;
                                JViewport viewport = scrollPane.getViewport();
                                Component comp = viewport.getView();
                                if (comp instanceof JTextArea) {
                                    JTextArea jTextArea = (JTextArea) comp;
                                    noidung = jTextArea.getText();
                                    if (!noidung.isEmpty()) {
                                        answered = true;
                                    }
                                }
                            }
                        }
                        
                        if (!answered) {
                            allAnswered = false;
                        }
                    }
                }
                
                QuanNhan quanNhan = new QuanNhan();
                quanNhan.setId(idQN);
                
                CauHoi cauHoi = new CauHoi();
                cauHoi.setId(idCauHoi);
                
                traLois.add(new TraLoi(noidung, quanNhan, cauHoi));
                
            }
            if(allAnswered){
                if(qndao.insertTraLoi(traLois) && !qndao.insetBKS_QN(idQN, idBKS)){
                    JOptionPane.showMessageDialog(null, "Thêm câu trả lời thành công");
                    KetQuaBKS.setVisible(true);
                    JInfoExam.setVisible(false);
                    JUserExam.setVisible(false);
                }else{
                    JOptionPane.showMessageDialog(null, "Thêm câu trả lời thất bại");
                }
            }else{
                JOptionPane.showMessageDialog(null, "Vui lòng trả lời hết tất cả các câu hỏi!");
            }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnQuayLaiBKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuayLaiBKSActionPerformed
        KetQuaBKS.setVisible(false);
        JUserExam.setVisible(true);
    }//GEN-LAST:event_btnQuayLaiBKSActionPerformed

    private void btnKetThucBKSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKetThucBKSActionPerformed
        
        String noidung = txtPhanHoi.getText();
        if(Validation.isEmpty(noidung)){
            JOptionPane.showMessageDialog(null, "Vui lòng điền ý kiến phản hồi của bạn !");
        }else{
            if(!noidung.equalsIgnoreCase("Không có") && !noidung.equalsIgnoreCase("Không") && !noidung.equalsIgnoreCase("Ko")){
                
                LocalDateTime now = LocalDateTime.now();
                DateTimeFormatter dateTimeFormatter = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss");
                String dateTimeStr = now.format(dateTimeFormatter);
                
                PhanHoi phanHoi = new PhanHoi(noidung, idBKS, idQN, LocalDateTime.parse(dateTimeStr.trim(), dateTimeFormatter));
                
                if(!qndao.insertPhanHoi(phanHoi)){
                    JOptionPane.showMessageDialog(null, "Cảm ơn bạn đã tham gia bài khảo sát của chúng tôi !");
                }
            }
            
            showDanhSachBKS();
            KetQuaBKS.setVisible(false);
            JInfoExam.setVisible(true);
        }
    }//GEN-LAST:event_btnKetThucBKSActionPerformed
 
    List<JRadioButton> radioButtonList = new ArrayList<>();
    private void showDanhSachBKS() {
        showDanhSachBKS.removeAll(); // Xóa tất cả các thành phần trong JPanel
        showDanhSachBKS.revalidate(); // Cập nhật giao diện người dùng
        showDanhSachBKS.repaint(); // Vẽ lại JPanel
        List<BaiKhaoSat> list = ksdao.selectBKSByCapBac(idQN,capbac);
        if(list != null){
            showDanhSachBKS.setLayout(new BoxLayout(showDanhSachBKS, BoxLayout.Y_AXIS));
            ButtonGroup buttonGroup = new ButtonGroup();
            for (BaiKhaoSat baiKhaoSat : list) {
                JRadioButton  radioButton = new JRadioButton (baiKhaoSat.getTieuDe());
                
                radioButton.setFont(new Font("Arial", Font.BOLD, 18));
                radioButton.setForeground(Color.WHITE);
                Insets margin = new Insets(50, 10, 20, 20); // đơn vị là pixel
                radioButton.setMargin(margin);
                
                radioButtonList.add(radioButton);
                
                buttonGroup.add(radioButton);
                showDanhSachBKS.add(radioButton);
                radioButton.putClientProperty("BaiKhaoSatID", baiKhaoSat.getId());
            }
        }else{
            btnStartExam.setVisible(false);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JInfoExam;
    private javax.swing.JPanel JUserExam;
    private javax.swing.JPanel KetQuaBKS;
    private javax.swing.JButton btnKetThucBKS;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.JButton btnQuayLaiBKS;
    private javax.swing.JButton btnStartExam;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jNumberQuestion;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jshowQuestion;
    private javax.swing.JPanel showDanhSachBKS;
    private javax.swing.JTextArea txtPhanHoi;
    private javax.swing.JLabel txtSoCau;
    // End of variables declaration//GEN-END:variables
}
